### PR TITLE
Refactor Memory Generator

### PR DESCRIPTION
**Pull request by DerangedMonkeyNinja**
Refactor the memory generator to improve performance and fix numerous issues.

Additionally, this PR contains a generic handler framework, which should eventually be used for all of the generators.

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/552)

### CODE REVIEW

**Review by jmkho-spirent — COMMENTED** [review]
> Reviewed 55 of 79 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/552)* status: 55 of 79 files reviewed, 3 unresolved discussions (waiting on @DerangedMonkeyNinja and @jmkho-spirent)

___
*[src/modules/memory/server.cpp, line 240 at r1](https://reviewable.io/reviews/spirent/openperf/552#-MxaoNTOAEOZskCr8h_m:-MxaoNTOAEOZskCr8h_n:b-bftjgm) ([raw file](https://github.com/spirent/openperf/blob/7d699f00e06b05f868efae529a04caf31a7f2964/src/modules/memory/server.cpp#L240)):*
> ```cpp
> }
> 
> reply_msg
> ```

nit: is it intentional to have the return type on a separate line here?
___
*[src/modules/memory/utils.cpp, line 72 at r1](https://reviewable.io/reviews/spirent/openperf/552#-MxavRmv-KMSc1Ex2kIO:-MxavRmv-KMSc1Ex2kIP:bs4r3tj) ([raw file](https://github.com/spirent/openperf/blob/7d699f00e06b05f868efae529a04caf31a7f2964/src/modules/memory/utils.cpp#L72)):*
> ```cpp
>     }
> 
>     if (config.getReadSize() < 0) {
> ```

read size of zero is only valid if reads per second is zero. Or we treat either value of zero to disable reads? It didn't seem that way from the coordinator code but might have missed something.
___
*[src/modules/memory/generator/buffer.hpp, line 18 at r1](https://reviewable.io/reviews/spirent/openperf/552#-MxawzQRDMIsGPAh_626:-MxawzQRDMIsGPAh_627:b30rxrb) ([raw file](https://github.com/spirent/openperf/blob/7d699f00e06b05f868efae529a04caf31a7f2964/src/modules/memory/generator/buffer.hpp#L18)):*
> ```cpp
> 
>     std::byte* data();
>     std::byte* data() const;
> ```

Shouldn't this be pointer to const std::byte to not allow modifying the data through the returned pointer?

**Review by DerangedMonkeyNinja — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/552)* status: 55 of 79 files reviewed, 2 unresolved discussions (waiting on @jmkho-spirent)

___
*[src/modules/memory/server.cpp, line 240 at r1](https://reviewable.io/reviews/spirent/openperf/552#-MxaoNTOAEOZskCr8h_m:-MxddTvF28IQGg19XA6C:b-6helac) ([raw file](https://github.com/spirent/openperf/blob/7d699f00e06b05f868efae529a04caf31a7f2964/src/modules/memory/server.cpp#L240)):*
<details><summary><i>Previously, jmkho-spirent (Jan-Michael Kho) wrote…</i></summary><blockquote>

nit: is it intentional to have the return type on a separate line here?
</blockquote></details>

The code is auto formatted, so... yes?
___
*[src/modules/memory/utils.cpp, line 72 at r1](https://reviewable.io/reviews/spirent/openperf/552#-MxavRmv-KMSc1Ex2kIO:-MxddoD4Auc1Gg0mbx5L:b-d6nauv) ([raw file](https://github.com/spirent/openperf/blob/7d699f00e06b05f868efae529a04caf31a7f2964/src/modules/memory/utils.cpp#L72)):*
<details><summary><i>Previously, jmkho-spirent (Jan-Michael Kho) wrote…</i></summary><blockquote>

read size of zero is only valid if reads per second is zero. Or we treat either value of zero to disable reads? It didn't seem that way from the coordinator code but might have missed something.
</blockquote></details>

I'll update it.
___
*[src/modules/memory/generator/buffer.hpp, line 18 at r1](https://reviewable.io/reviews/spirent/openperf/552#-MxawzQRDMIsGPAh_626:-MxdeCYvDKGtRB4vpPJn:b2nhswy) ([raw file](https://github.com/spirent/openperf/blob/7d699f00e06b05f868efae529a04caf31a7f2964/src/modules/memory/generator/buffer.hpp#L18)):*
<details><summary><i>Previously, jmkho-spirent (Jan-Michael Kho) wrote…</i></summary><blockquote>

Shouldn't this be pointer to const std::byte to not allow modifying the data through the returned pointer?
</blockquote></details>

Yes

**Review by DerangedMonkeyNinja — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/552)* status: 52 of 79 files reviewed, 2 unresolved discussions (waiting on @jmkho-spirent)

___
*[src/modules/memory/utils.cpp, line 72 at r1](https://reviewable.io/reviews/spirent/openperf/552#-MxavRmv-KMSc1Ex2kIO:-Mxdh0M7D2niGudp8zBK:bb6un1j) ([raw file](https://github.com/spirent/openperf/blob/7d699f00e06b05f868efae529a04caf31a7f2964/src/modules/memory/utils.cpp#L72)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

I'll update it.
</blockquote></details>

Done
___
*[src/modules/memory/generator/buffer.hpp, line 18 at r1](https://reviewable.io/reviews/spirent/openperf/552#-MxawzQRDMIsGPAh_626:-MxdiiW_9a8dUi12hJYm:bb6un1j) ([raw file](https://github.com/spirent/openperf/blob/7d699f00e06b05f868efae529a04caf31a7f2964/src/modules/memory/generator/buffer.hpp#L18)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Done

**Review by jmkho-spirent — COMMENTED** [review]
:lgtm:

> Reviewed 24 of 79 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/552#-:-MxePizP9EV3ngS90mxg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DerangedMonkeyNinja)

**Pull request merged**
