### PR TITLE
Added most of deb and rpm packaging (WIP)

### PR DESCRIPTION
**Pull request by smprogsoft**
This pull requirest is not meant to be merged at this time. With these changes, I am basically creating a staging area under the `build` directory to build the package (both for the Debian and the RPM). There was a lot of time spent just figuring out the minimal files needed on the Debian side. Dave mentioned the `orion-api` repo which was helpful. There are a couple of things I know I still need to address:

- The version of the package (e.g. `0.1.0`) is currently hardcoded. Timmons mentioned that I can execute the `openperf` executable with the `--version` option to get that.
- I have not been able to actually run `openperf` yet so I am not sure what the `config.yaml` file for an initial installation would look like. I have files as placeholders now.
- I tried the RPM package on a Centos VM. It did not work due to a `libc.so.6` requirement. I guess I naively thought I would be able to build the RPM on a Debian system and run it on Centos. I need to look more into this.

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/391)

### CODE REVIEW

**Review by smprogsoft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/391)* status: 0 of 16 files reviewed, 3 unresolved discussions

___
*[pkg/Makefile, line 3 at r1](https://reviewable.io/reviews/spirent/openperf/391#-MMXnnyM92Ilp6nDofsZ:-MMXnnyN8P4s6MGOv2vt:b-w6pmu8) ([raw file](https://github.com/spirent/openperf/blob/4ffcdf978afff584e4aaceb45666a3b79d07de6b/pkg/Makefile#L3)):*
> ```Makefile
> 
> # SM TODO: Not sure where this is to come from
> VERSION ?= 0.1.0
> ```

Still need to add this. It probably will not be here any longer since, if I run `openperf` to get its version, I need to know the full path to the `openperf` executable being packaged and I don't have that here. Once I have the executable, I was planning to do something like this:

# Get the openperf version.
# $1 - Full path to the openperf binary.
define get_version
$(shell
	$(1)/openperf --version 2>& 1 | \
	head -n 1 | \
	sed -e 's/^.*version v//g;' -e 's/-.*$$//;'
)
endef
___
*[pkg/debian/config.yaml, line 1 at r1](https://reviewable.io/reviews/spirent/openperf/391#-MMXnb6cBRm90j1szUx8:-MMXnb6cBRm90j1szUx9:b-brjkn3) ([raw file](https://github.com/spirent/openperf/blob/4ffcdf978afff584e4aaceb45666a3b79d07de6b/pkg/debian/config.yaml#L1)):*
> ```YAML
> core:
> ```

Placeholder for now.
___
*[pkg/rpm/config.yaml, line 1 at r1](https://reviewable.io/reviews/spirent/openperf/391#-MMXnhut43PrdGNu8wJr:-MMXnhut43PrdGNu8wJs:b47b8r1) ([raw file](https://github.com/spirent/openperf/blob/4ffcdf978afff584e4aaceb45666a3b79d07de6b/pkg/rpm/config.yaml#L1)):*
> ```YAML
> core:
> ```

Placeholder for now

**Review by smprogsoft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/391)* status: 0 of 16 files reviewed, 3 unresolved discussions

___
*[pkg/Makefile, line 3 at r1](https://reviewable.io/reviews/spirent/openperf/391#-MMXobgW-R-9E64Dwz2k:-MMXobgW-R-9E64Dwz2l:bqzj12i) ([raw file](https://github.com/spirent/openperf/blob/4ffcdf978afff584e4aaceb45666a3b79d07de6b/pkg/Makefile#L3)):*
> ```Makefile
> 
> # SM TODO: Not sure where this is to come from
> VERSION ?= 0.1.0
> ```

Still need to add this. It probably will not be here any longer since, if I run openperf to get its version, I need to know the full path to the openperf executable being packaged and I don't have that here. Once I have the executable, I was planning to do something like this:

```
# Get the openperf version.
# $1 - Full path to the openperf binary.
define get_version
$(shell
	$(1)/openperf --version 2>& 1 | \
	head -n 1 | \
	sed -e 's/^.*version v//g;' -e 's/-.*$$//;'
)
endef
```

**Review by djoyner — CHANGES_REQUESTED** [review]
> Reviewed 5 of 16 files at r1, 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/391)* status: 8 of 17 files reviewed, 6 unresolved discussions (waiting on @smprogsoft)

___
*[pkg/common.mk, line 22 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOI61C3qNGyNHL018-:-MNOI61C3qNGyNHL0180:b-mz4l0n) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/common.mk#L22)):*
> ```Makefile
> VERSION_SRC	:= $(abspath $(OP_ROOT)/build/openperf-$(PLATFORM)-$(ARCH)-$(MODE)/bin/openperf)
> ifeq ($(wildcard $(VERSION_SRC)),$(VERSION_SRC))
> 	VERSION := $(shell $(VERSION_SRC) --version 2>&1 | head -n 1 \
> ```

It looks like `openperf` spits out `$BUILD_VERSION` which is defined as `$GIT_VERSION`. Maybe use that instead of executing the binary?
___
*[pkg/Makefile, line 3 at r1](https://reviewable.io/reviews/spirent/openperf/391#-MMXobgW-R-9E64Dwz2k:-MNOIyfaE4v5N9dQ3f5Q:b-stm74b) ([raw file](https://github.com/spirent/openperf/blob/4ffcdf978afff584e4aaceb45666a3b79d07de6b/pkg/Makefile#L3)):*
<details><summary><i>Previously, smprogsoft wrote…</i></summary><blockquote>

Still need to add this. It probably will not be here any longer since, if I run openperf to get its version, I need to know the full path to the openperf executable being packaged and I don't have that here. Once I have the executable, I was planning to do something like this:

```
# Get the openperf version.
# $1 - Full path to the openperf binary.
define get_version
$(shell
	$(1)/openperf --version 2>& 1 | \
	head -n 1 | \
	sed -e 's/^.*version v//g;' -e 's/-.*$$//;'
)
endef
```
</blockquote></details>

See earlier suggestion (use `$GIT_VERSION`).
___
*[pkg/debian/config.yaml, line 1 at r1](https://reviewable.io/reviews/spirent/openperf/391#-MMXnb6cBRm90j1szUx8:-MNOJ9wvD44Wm5Jij93P:b-3qwj6r) ([raw file](https://github.com/spirent/openperf/blob/4ffcdf978afff584e4aaceb45666a3b79d07de6b/pkg/debian/config.yaml#L1)):*
<details><summary><i>Previously, smprogsoft wrote…</i></summary><blockquote>

Placeholder for now.
</blockquote></details>

Not sure if it is possible to ship a "one size fits all" config or whether we should ship a well-commented example (or both). Timmons, your opinion?
___
*[pkg/debian/templates/changelog, line 3 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOJdiO9RXzO_YPNDPd:-MNOJdiO9RXzO_YPNDPe:bmtyyqx) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/debian/templates/changelog#L3)):*
> ```
> openperf ({{VERSION}}-{{PKG_VERSION}}) UNRELEASED; urgency=low
> 
>   * Initial release.
> ```

Should this come from `git` history? How do other projects handle this?
___
*[pkg/debian/templates/control, line 6 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOJnmxDUFKwQCWx9wW:-MNOJnmxDUFKwQCWx9wX:b-9hz7x0) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/debian/templates/control#L6)):*
> ```
> Maintainer: Spirent Builder <support@spirent.com>
> Build-Depends: debhelper (>=11~)
> Standards-Version: 4.1.4
> ```

Is this a Debian thing?

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 7 of 16 files at r1, 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/391)* status: all files reviewed, 13 unresolved discussions (waiting on @smprogsoft)

___
*[pkg/common.mk, line 5 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOSwes9VxB8yugt4CG:-MNOSwes9VxB8yugt4CH:bmmwz68) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/common.mk#L5)):*
> ```Makefile
> # This file expects the following values to be defined
> # (Note: the handle op_check_var define is not available yet)
> ifeq ($(PKG_TYPE),)
> ```

Package specific variables should go in the packaging makefile.  Only variables required for multiple high level targets should go here.
___
*[pkg/Makefile, line 21 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOTxt4EmfEY8k3zdaR:-MNOTxt4EmfEY8k3zdaS:b3dnyay) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/Makefile#L21)):*
> ```Makefile
> 
> package-debian:
> 	cd debian && $(MAKE) all
> ```

Please be consistent with naming here.  'debian' is a distribution, but 'rpm' is a packaging format.  I'd prefer to see all the targets named after the platform or after the packaging, but not a mix of both.
___
*[pkg/debian/config.yaml, line 1 at r1](https://reviewable.io/reviews/spirent/openperf/391#-MMXnb6cBRm90j1szUx8:-MNOTHKVAfMFn4kDXYBp:bxdqvqx) ([raw file](https://github.com/spirent/openperf/blob/4ffcdf978afff584e4aaceb45666a3b79d07de6b/pkg/debian/config.yaml#L1)):*
<details><summary><i>Previously, djoyner (David Joyner) wrote…</i></summary><blockquote>

Not sure if it is possible to ship a "one size fits all" config or whether we should ship a well-commented example (or both). Timmons, your opinion?
</blockquote></details>

Yes, I think a well commented example is a good idea.
___
*[pkg/debian/install.mk, line 7 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOTces2eAeSBSl6P50:-MNOTces2eAeSBSl6P51:b-6awexd) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/debian/install.mk#L7)):*
> ```Makefile
> include ../vars.mk
> 
> # Pull in common build varables (requires OP_ROOT to be defined)
> ```

These two lines appear to be contradictory, since the next line sets OP_ROOT if it hasn't been set already.
___
*[pkg/debian/Makefile, line 15 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOUPsi0pOkuYQSSgw-:-MNOUPsi0pOkuYQSSgw0:b8w83xq) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/debian/Makefile#L15)):*
> ```Makefile
> ifeq ($(ARCH),x86_64)
> 	PKG_ARCH := amd64
> endif
> ```

Suggest adding an else branch here with an error message noting that other platforms are unsupported.  We don't support arm builds yet, but they're coming soon.
___
*[pkg/debian/Makefile, line 64 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOUm7d6hBM-TD1G3cQ:-MNOUm7d6hBM-TD1G3cR:b5ruuid) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/debian/Makefile#L64)):*
> ```Makefile
> # $2: The to copy the file to. If any parent directories are missing, they will be created. The
> # 	file is copied to preserve file permissions and its timestamp. Any supported template parameters
> #	found in the file will be replaced.
> ```

nit: white space
___
*[pkg/debian/templates/lintian-overrides, line 7 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOV4mO5PC-OOms15ll:-MNOV4mO5PC-OOms15lm:bx4uznm) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/debian/templates/lintian-overrides#L7)):*
> ```
> openperf: new-package-should-close-itp-bug
> openperf: sharedobject-in-library-directory-missing-soname usr/lib/libopenperf-shim.so
> openperf: binary-without-manpage usr/bin/openperf
> ```

Should we add a man page?
___
*[pkg/rpm/Makefile, line 63 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOVF_C1CS7bgBvT8hE:-MNOVF_D0HAul27o6E7G:b8bqqdz) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/rpm/Makefile#L63)):*
> ```Makefile
> # $2: The to copy the file to. If any parent directories are missing, they will be created. The
> # 	file is copied to preserve file permissions and its timestamp. Any supported template parameters
> #	found in the file will be replaced.
> ```

nit: whitespace

**Review by djoyner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/391)* status: all files reviewed, 13 unresolved discussions (waiting on @DerangedMonkeyNinja and @smprogsoft)

___
*[pkg/debian/templates/lintian-overrides, line 7 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOV4mO5PC-OOms15ll:-MNOVyRdEdFEH4m74ZqX:ba9snar) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/debian/templates/lintian-overrides#L7)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Should we add a man page?
</blockquote></details>

Yes, but this is outside the scope of what he's working on here. Create an issue...

**Review by smprogsoft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/391)* status: 2 of 18 files reviewed, 9 unresolved discussions (waiting on @DerangedMonkeyNinja, @djoyner, and @smprogsoft)

___
*[pkg/common.mk, line 5 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOSwes9VxB8yugt4CG:-MNUooIP6Ire3VQ717pa:b4wv27e) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/common.mk#L5)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Package specific variables should go in the packaging makefile.  Only variables required for multiple high level targets should go here.
</blockquote></details>

Sorry, I am not sure what the issue is that you are pointing out. This file is included into the package-specific (deb, rpm) makefiles. The PKG_TYPE is just an "input" parameter to this include makefile file. It is used to ensure that the package files have a unique place within the build directory.
___
*[pkg/common.mk, line 22 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOI61C3qNGyNHL018-:-MNUpVITClzghL2_cQlB:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/common.mk#L22)):*
<details><summary><i>Previously, djoyner (David Joyner) wrote…</i></summary><blockquote>

It looks like `openperf` spits out `$BUILD_VERSION` which is defined as `$GIT_VERSION`. Maybe use that instead of executing the binary?
</blockquote></details>

Done.
___
*[pkg/Makefile, line 3 at r1](https://reviewable.io/reviews/spirent/openperf/391#-MMXobgW-R-9E64Dwz2k:-MNUpa5Y-A5v7y1NvGwP:bb6un1j) ([raw file](https://github.com/spirent/openperf/blob/4ffcdf978afff584e4aaceb45666a3b79d07de6b/pkg/Makefile#L3)):*
<details><summary><i>Previously, djoyner (David Joyner) wrote…</i></summary><blockquote>

See earlier suggestion (use `$GIT_VERSION`).
</blockquote></details>

Done
___
*[pkg/Makefile, line 21 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOTxt4EmfEY8k3zdaR:-MNUpcDH5ykk7xYfRYc_:bmhez8r) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/Makefile#L21)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Please be consistent with naming here.  'debian' is a distribution, but 'rpm' is a packaging format.  I'd prefer to see all the targets named after the platform or after the packaging, but not a mix of both.
</blockquote></details>

Good point. Changed to "deb" and "rpm" (package type extensions)
___
*[pkg/debian/templates/changelog, line 3 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOJdiO9RXzO_YPNDPd:-MNUqAnf1y9Bme0tFuvL:bloin7f) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/debian/templates/changelog#L3)):*
<details><summary><i>Previously, djoyner (David Joyner) wrote…</i></summary><blockquote>

Should this come from `git` history? How do other projects handle this?
</blockquote></details>

From what I have seen, people pretty much just use the git history. I have added a script that does the same thing such that the changelog is now generated.
___
*[pkg/debian/install.mk, line 7 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOTces2eAeSBSl6P50:-MNUpsq0C3JMev0HK1rX:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/debian/install.mk#L7)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

These two lines appear to be contradictory, since the next line sets OP_ROOT if it hasn't been set already.
</blockquote></details>

Done.
___
*[pkg/debian/Makefile, line 15 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOUPsi0pOkuYQSSgw-:-MNUpvoe7he1cTiQ0jFm:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/debian/Makefile#L15)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Suggest adding an else branch here with an error message noting that other platforms are unsupported.  We don't support arm builds yet, but they're coming soon.
</blockquote></details>

Done.
___
*[pkg/debian/templates/control, line 6 at r2](https://reviewable.io/reviews/spirent/openperf/391#-MNOJnmxDUFKwQCWx9wW:-MNUsBTmESTVgEnGlar3:b-ajymf1) ([raw file](https://github.com/spirent/openperf/blob/73fc35e5be3b8d879c97e522be467084961e86e0/pkg/debian/templates/control#L6)):*
> ```
> Standards-Version
> ```
Yes. It was added by the tools I used to create the initial files. https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-standards-version

**Review by smprogsoft — COMMENTED** [review]
I still have a question about how you would like to ultimately build the packages. To get the package to work on CentOS 7, I had to install a different set of packages into a CentOS 7 based "build" container. I could not build the rpm from the Debian container (based on the build container in the repo) because the binary ended up requiring a newer libc.so (v6) than what was available. I was building for CentOS 7 though, and maybe that is too old (should I target a CentOS 8 for the build?) 

If you want to build using different "build" containers (as I have done), I wanted to get your ideas on how you would want to set that up for a Jenkins type build. One thought I had was to have build containers that mount a volume where the source can be found. We could have two build containers, both would build from the same source. The only catch would be having to make sure the output build directory is unique for each container. I thought that could be done by changing the `mk/build.mk` file so that the build directory name "build" is overridable (i.e. `BUILD_DIR?=build`). Then we could adjust the output directory by setting the variable in each of the specific build containers.

Thoughts?

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/391#-:-MNVmNNn89W5sEFM1RJq:blh7ahd)* status: 2 of 18 files reviewed, 9 unresolved discussions (waiting on @DerangedMonkeyNinja, @djoyner, and @smprogsoft)

**Review by djoyner — COMMENTED** [review]
> Reviewed 6 of 17 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/391)* status: 8 of 18 files reviewed, 6 unresolved discussions (waiting on @DerangedMonkeyNinja, @djoyner, and @smprogsoft)

**Review by djoyner — COMMENTED** [review]
@smprogsoft I think you're on the right track w/r/t using CentOS-specific build environments to produce RPMs. In terms of productionizing (is that a word?) the CI jobs, I would set up a job per build environment rather than trying to tie a bunch of environments together under the banner of a single job. That would get messy and may not even be possible in some CI systems.

More to the point, I discussed with Justin offline and we agree that it's ok to shelve the CentOS/RPM build for now. If you can keep what you have (e.g. on a branch for later reference), that would be good.

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/391#-:-MN_K17JAJU8-UWaMXta:bms1rnd)* status: 8 of 18 files reviewed, 6 unresolved discussions (waiting on @DerangedMonkeyNinja, @djoyner, and @smprogsoft)

**Review by smprogsoft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/391)* status: 8 of 18 files reviewed, 6 unresolved discussions (waiting on @DerangedMonkeyNinja, @djoyner, and @smprogsoft)

___
*[pkg/debian/config.yaml, line 1 at r1](https://reviewable.io/reviews/spirent/openperf/391#-MMXnb6cBRm90j1szUx8:-MNkUM241r0Ogifrnabp:b-humutd) ([raw file](https://github.com/spirent/openperf/blob/4ffcdf978afff584e4aaceb45666a3b79d07de6b/pkg/debian/config.yaml#L1)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Yes, I think a well commented example is a good idea.
</blockquote></details>

I have been holding off on dealing with the `config.yaml` file (since we will essentially have to generate parts of the acting `config.yaml` file and cobble together other parts anyway and I am looking into that aspect). What would be an acceptable example file? Should I just take the content from the following: `configuration.md` file and make an example yaml file from that with the comments from the file?

(The changes for the `config.yaml` file will be coming in a deb only package PR.)

**Comment by smprogsoft** [comment]
Submitted a different pull request with only the deb packaging support (see https://github.com/Spirent/openperf/pull/419).

**Pull request closed without merging**
