### PR TITLE
Arm64 support

### PR DESCRIPTION
**Pull request by DerangedMonkeyNinja**
Update OpenPerf to support ARM64 platforms and add the ability to cross-compile from x86 hosts.

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/485)

### CODE REVIEW

**Review by DerangedMonkeyNinja — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/485)* status: 0 of 100 files reviewed, 1 unresolved discussion (waiting on @cmyers-spirent and @dmorton-spirent)

*[a discussion](https://reviewable.io/reviews/spirent/openperf/485#-MYkB3YVEWxwV689C2L2:-MYkB3YVEWxwV689C2L3:bjn50uy) (no related file):*
Most of the actual changes here don't change functionality.  They're just needed to work with older or newer toolchains when cross-compiling.  The modules ported from inception were especially problematic and I had to remove lots of header includes to get the code to compile cleanly.

If you see any Octeon related or functional changes, please comment.  They shouldn't be here. The obvious exception being ARM64/NEON support for `lib/spirent_pga` and `modules/cpu`. 

---

**Review by DerangedMonkeyNinja — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/485)* status: 0 of 100 files reviewed, 1 unresolved discussion (waiting on @cmyers-spirent and @dmorton-spirent)

*[a discussion](https://reviewable.io/reviews/spirent/openperf/485#-MYkB3YVEWxwV689C2L2:-MYkBp8ZDkdb0bKzdA4q:bz9w9r0) (no related file):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Most of the actual changes here don't change functionality.  They're just needed to work with older or newer toolchains when cross-compiling.  The modules ported from inception were especially problematic and I had to remove lots of header includes to get the code to compile cleanly.

If you see any Octeon related or functional changes, please comment.  They shouldn't be here. The obvious exception being ARM64/NEON support for `lib/spirent_pga` and `modules/cpu`. 
</blockquote></details>

This change also adds an ARM64 cross compilation to CircleCi.  Don't want the build to regress after this point. ;-p

---

**Review by cmyers-spirent — APPROVED** [review]
> Reviewed 100 of 100 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/485)* status: all files reviewed, 3 unresolved discussions (waiting on @DerangedMonkeyNinja and @dmorton-spirent)

___
*[src/framework/utils/filesystem.hpp, line 14 at r1](https://reviewable.io/reviews/spirent/openperf/485#-MYkJhYA3hXM4G1vFOXS:-MYkJhYA3hXM4G1vFOXT:b8rkz8e) ([raw file](https://github.com/spirent/openperf/blob/b377704348f6073595800c79880ef8f4bf57569b/src/framework/utils/filesystem.hpp#L14)):*
> ```cpp
> #define HAVE_EXPERIMENTAL_FILESYSTEM 1
> #endif
> ```

yuck.  I thought filesystem was part of C++ 17 standard library.
___
*[src/modules/tvlp/controller_stack.hpp, line 11 at r1](https://reviewable.io/reviews/spirent/openperf/485#-MYkLkQM-M--1tO-7ZSD:-MYkLkQN-OYrbNtPSpC1:b9ly3z8) ([raw file](https://github.com/spirent/openperf/blob/b377704348f6073595800c79880ef8f4bf57569b/src/modules/tvlp/controller_stack.hpp#L11)):*
> ```cpp
> 
> #include "tl/expected.hpp"
> ```

I guess these comments could be deleted now?

**Review by DerangedMonkeyNinja — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/485)* status: all files reviewed, 1 unresolved discussion (waiting on @dmorton-spirent)

___
*[src/framework/utils/filesystem.hpp, line 14 at r1](https://reviewable.io/reviews/spirent/openperf/485#-MYkJhYA3hXM4G1vFOXS:-MYke-Fq5f1BvkEmOrMQ:b-2vmnv3) ([raw file](https://github.com/spirent/openperf/blob/b377704348f6073595800c79880ef8f4bf57569b/src/framework/utils/filesystem.hpp#L14)):*
<details><summary><i>Previously, cmyers-spirent wrote…</i></summary><blockquote>

yuck.  I thought filesystem was part of C++ 17 standard library.
</blockquote></details>

It is, however libstdc++7 only has a partial implementation of the c++17 standard and that's the toolchain I had to use for the OcteonTX2 port.
___
*[src/modules/tvlp/controller_stack.hpp, line 11 at r1](https://reviewable.io/reviews/spirent/openperf/485#-MYkLkQM-M--1tO-7ZSD:-MYkeJ56-GPc5f2RJQ9q:b-rvux49) ([raw file](https://github.com/spirent/openperf/blob/b377704348f6073595800c79880ef8f4bf57569b/src/modules/tvlp/controller_stack.hpp#L11)):*
<details><summary><i>Previously, cmyers-spirent wrote…</i></summary><blockquote>

I guess these comments could be deleted now?
</blockquote></details>

Yep; must have missed them. D'oh!

**Review by dmorton-spirent — APPROVED** [review]
> Reviewed 99 of 100 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/485)* status: all files reviewed, 3 unresolved discussions (waiting on @DerangedMonkeyNinja)

___
*[mk/mode/testing.mk, line 5 at r1](https://reviewable.io/reviews/spirent/openperf/485#-MYkg83gBj54RbzDGoxJ:-MYkg83gBj54RbzDGoxK:b5g608c) ([raw file](https://github.com/spirent/openperf/blob/b377704348f6073595800c79880ef8f4bf57569b/mk/mode/testing.mk#L5)):*
> ```Makefile
> #
> 
> #OP_COPTS += -Os -gline-tables-only
> ```

Nit: did you meant to leave the old line here?
___
*[src/framework/utils/memcpy.hpp, line 7 at r1](https://reviewable.io/reviews/spirent/openperf/485#-MYkgxjA9EZBtdYgugiJ:-MYkgxjA9EZBtdYgugiK:b104eo4) ([raw file](https://github.com/spirent/openperf/blob/b377704348f6073595800c79880ef8f4bf57569b/src/framework/utils/memcpy.hpp#L7)):*
> ```cpp
> #include <cstring>
> 
> /* Turn compiler generated instruction set macros into constexpr booleans */
> ```

Minor: File looks like it's only for x86. Is there anything comparable for ARM we ought to look at including?

**Review by dmorton-spirent — COMMENTED** [review]
Did you update the `Dockerfile` to pull in the `aarch64` toolchain? I see the updated image on docker hub but not the updated file.

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/485#-:-MYkodHyACwA9W83FE0C:bwezo31)* status: all files reviewed, 3 unresolved discussions (waiting on @DerangedMonkeyNinja)

**Review by DerangedMonkeyNinja — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/485)* status: all files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

___
*[mk/mode/testing.mk, line 5 at r1](https://reviewable.io/reviews/spirent/openperf/485#-MYkg83gBj54RbzDGoxJ:-MYkwUw1CBzURmF4NZA8:b-43vzxh) ([raw file](https://github.com/spirent/openperf/blob/b377704348f6073595800c79880ef8f4bf57569b/mk/mode/testing.mk#L5)):*
<details><summary><i>Previously, dmorton-spirent (Dan Morton) wrote…</i></summary><blockquote>

Nit: did you meant to leave the old line here?
</blockquote></details>

Probably not.  I think I had to remove it for the octeon compiler.  Let me check this and update if necessary.  Good catch!
___
*[src/framework/utils/memcpy.hpp, line 7 at r1](https://reviewable.io/reviews/spirent/openperf/485#-MYkgxjA9EZBtdYgugiJ:-MYkwD8O7wTIZE1Mu8WB:bbepk5c) ([raw file](https://github.com/spirent/openperf/blob/b377704348f6073595800c79880ef8f4bf57569b/src/framework/utils/memcpy.hpp#L7)):*
<details><summary><i>Previously, dmorton-spirent (Dan Morton) wrote…</i></summary><blockquote>

Minor: File looks like it's only for x86. Is there anything comparable for ARM we ought to look at including?
</blockquote></details>

I couldn't find anything. DPDK has NEON enabled `memcpy` routines, but there's a note saying you need to benchmark them on your system because they could be slower plus a lot of options to toggle.  Figured it would be safer to just use the system `memcpy` for ARM.

**Review by DerangedMonkeyNinja — COMMENTED** [review]
It was in a separate PR.  I needed to get it merged in before this so that CircleCI could run the aarch64 build.

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/485#-:-MYkwdZV6L_DPldPI6ea:b-z37jh9)* status: all files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

**Review by dmorton-spirent — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/485#-:-MYkxGw2BJ2sd6scFEFc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

___
*[src/framework/utils/memcpy.hpp, line 7 at r1](https://reviewable.io/reviews/spirent/openperf/485#-MYkgxjA9EZBtdYgugiJ:-MYkxDDTA798cioKtsVp:bfb2anf) ([raw file](https://github.com/spirent/openperf/blob/b377704348f6073595800c79880ef8f4bf57569b/src/framework/utils/memcpy.hpp#L7)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

I couldn't find anything. DPDK has NEON enabled `memcpy` routines, but there's a note saying you need to benchmark them on your system because they could be slower plus a lot of options to toggle.  Figured it would be safer to just use the system `memcpy` for ARM.
</blockquote></details>

Sounds good, thanks for the info.

**Review by cmyers-spirent — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/485)* status: all files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

**Review by cmyers-spirent — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/485)* status: all files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

**Review by cmyers-spirent — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/485)* status: all files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

**Review by cmyers-spirent — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/485#-:-MYl5vbaEdsKR2Gg7yma:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

**Pull request merged**
