### PR TITLE
Preparing to load modules dynamically at runtime.

### PR DESCRIPTION
**Pull request by abelov-spirent**
Signed-off-by: Artem Belov <artem.belov@spirent.com>

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/324)

### CODE REVIEW

**Comment by abelov-spirent** [comment]
Checked on TVLP #325

**Review by abelov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/324)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @DerangedMonkeyNinja)

___
*[mk/swagger_model.mk, line 13 at r1](https://reviewable.io/reviews/spirent/openperf/324#-MFpbrQn-d13QJ414Aac:-MG7qCYq8gE4OyBz_qhT:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/9c6ff9057647d8d0b4bd95b9ad2894ddf53135b3/mk/swagger_model.mk#L13)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

This variable name could be confusing since it's not passed to the linker at all.  Suggest renaming it to SWAGGER_FLAGS.
</blockquote></details>

Done.
___
*[src/framework/core/op_modules.h, line 67 at r1](https://reviewable.io/reviews/spirent/openperf/324#-MFpdJftEUoyMqiVji7B:-MG7qX94D7q7nDk4i9GM:bb0s6gg) ([raw file](https://github.com/spirent/openperf/blob/9c6ff9057647d8d0b4bd95b9ad2894ddf53135b3/src/framework/core/op_modules.h#L67)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

The documentation for this function is incorrect.  Additionally, I think this function should have a return code.  An error in module loading should be fatal, since that's an environmental problem the user needs to fix.
</blockquote></details>

What if directory contains some *.so file that is not a plugin module? For example somebody will put plugins to `lib` folder. Logged error message will show broken file, I that that should be enought, isn't it?
___
*[src/framework/core/op_modules.c, line 29 at r1](https://reviewable.io/reviews/spirent/openperf/324#-MFpb0PWB3Wa-tsVAfXs:-MG8GS7k1I6hbfK9cxZx:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/9c6ff9057647d8d0b4bd95b9ad2894ddf53135b3/src/framework/core/op_modules.c#L29)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Linux-isms aren't acceptable in the framework code. You need to restrict the code here to the POSIX API. If that's not possible, then create a wrapper function and compile in OS specific code as needed. Take a look at `framework/core/op_event_loop*` or `framework/core/op_thread*`.
</blockquote></details>

Done.
___
*[src/framework/core/op_modules.c, line 95 at r1](https://reviewable.io/reviews/spirent/openperf/324#-MFpd4zaENIRBH6Oc4O-:-MG7rynx4nm1JAjxtr_U:b-b9bxs4) ([raw file](https://github.com/spirent/openperf/blob/9c6ff9057647d8d0b4bd95b9ad2894ddf53135b3/src/framework/core/op_modules.c#L95)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

I don't think these casts for path are necessary, are they?
</blockquote></details>

It is just to check that file is `*.so`. Do you think it is not required?

**Review by abelov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/324)* status: 3 of 10 files reviewed, 5 unresolved discussions (waiting on @DerangedMonkeyNinja)

___
*[src/framework/core/directory.mk, line 2 at r2](https://reviewable.io/reviews/spirent/openperf/324#-MGAEuop6BtGgnFY_IJ_:-MGHZiPmBwAZYP_uH1-b:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/058c426f148661cf21844a205054672e85af03b3/src/framework/core/directory.mk#L2)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

This library should be added to FW_LDLIBS in the linux section of the makefile.
</blockquote></details>

Done.
___
*[src/framework/core/op_modules.h, line 67 at r1](https://reviewable.io/reviews/spirent/openperf/324#-MFpdJftEUoyMqiVji7B:-MGNfs1p0lZXcVgumqaY:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/9c6ff9057647d8d0b4bd95b9ad2894ddf53135b3/src/framework/core/op_modules.h#L67)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Whatever modules are loaded should come from an explicit configuration. Blindly loading modules from a directory is not acceptable as modules are likely to have dependencies and those can't be resolved by just loading them in some random order.
</blockquote></details>

Done.
___
*[src/framework/core/op_modules.c, line 95 at r1](https://reviewable.io/reviews/spirent/openperf/324#-MFpd4zaENIRBH6Oc4O-:-MGNfuOXD7Oja14lxarB:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/9c6ff9057647d8d0b4bd95b9ad2894ddf53135b3/src/framework/core/op_modules.c#L95)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

No, checking for the `.so` extension is a good idea. But, you don't need to cast path to (const char*) in `strrchr` above, do you?
</blockquote></details>

Done.
___
*[src/framework/core/op_modules.c, line 23 at r2](https://reviewable.io/reviews/spirent/openperf/324#-MGAFoo-ABA-k_t2mEKq:-MGNftXV7uhgc0r3rYuE:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/058c426f148661cf21844a205054672e85af03b3/src/framework/core/op_modules.c#L23)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

What is this global variable for?
</blockquote></details>

Done.
___
*[tests/unit/Makefile, line 46 at r2](https://reviewable.io/reviews/spirent/openperf/324#-MGAGulh8D81F5mMduqY:-MGNfx5Y5-D7lOVjmlRR:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/058c426f148661cf21844a205054672e85af03b3/tests/unit/Makefile#L46)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

This linker flag needs to only be added for Linux builds.
</blockquote></details>

Done.

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/324)* status: all files reviewed, 5 unresolved discussions (waiting on @abelov-spirent)

___
*[src/framework/core/op_init.c, line 74 at r3](https://reviewable.io/reviews/spirent/openperf/324#-MGPpVrY4LQLkS3GjmSj:-MGPpQ0LBX8SbfGgO_xh:bfvizzr) ([raw file](https://github.com/spirent/openperf/blob/a8f30781fcf5e2bfa4e037a86d1877e98029ec9b/src/framework/core/op_init.c#L74)):*
> ```C
> 
>     /* Load plugin modules */
>     op_modules_load(argc, argv);
> ```

Using the comments below will allow you to revert the signature change here.
___
*[src/framework/core/op_modules.c, line 33 at r3](https://reviewable.io/reviews/spirent/openperf/324#-MGPo-fy46OVhGpHlhp9:-MGPo-fz6rbJY9Og447d:b-3fht3r) ([raw file](https://github.com/spirent/openperf/blob/a8f30781fcf5e2bfa4e037a86d1877e98029ec9b/src/framework/core/op_modules.c#L33)):*
> ```C
>     op_modules_list_head = SLIST_HEAD_INITIALIZER(op_modules_list_head);
> 
> static const size_t op_modules_err_str_max_len = 144;
> ```

I didn't notice this before...  What's the rationale for this length?
___
*[src/framework/core/op_plugins.cpp, line 18 at r3](https://reviewable.io/reviews/spirent/openperf/324#-MGPom_S4Yq5_KTbxGzO:-MGPom_S4Yq5_KTbxGzP:b-4z0eem) ([raw file](https://github.com/spirent/openperf/blob/a8f30781fcf5e2bfa4e037a86d1877e98029ec9b/src/framework/core/op_plugins.cpp#L18)):*
> ```cpp
> find_plugin_modules_path(int argc __attribute__((unused)), char* const argv[])
> {
>     auto path = std::filesystem::canonical(std::filesystem::path(argv[0]))
> ```

Prefer you use `getcwd` for the working path name.
___
*[src/framework/core/op_plugins.cpp, line 20 at r3](https://reviewable.io/reviews/spirent/openperf/324#-MGPp3NYDtNwKn_Etr54:-MGPp3NYDtNwKn_Etr55:b-5zb3cn) ([raw file](https://github.com/spirent/openperf/blob/a8f30781fcf5e2bfa4e037a86d1877e98029ec9b/src/framework/core/op_plugins.cpp#L20)):*
> ```cpp
>     auto path = std::filesystem::canonical(std::filesystem::path(argv[0]))
>                     .remove_filename();
>     path += "../plugins";
> ```

Not sure I understand this...  You're looking for plugins in a parent directory?
___
*[src/framework/core/op_plugins.cpp, line 32 at r3](https://reviewable.io/reviews/spirent/openperf/324#-MGPoVDp67PfxwMXdjVs:-MGPoVDp67PfxwMXdjVt:bagtaox) ([raw file](https://github.com/spirent/openperf/blob/a8f30781fcf5e2bfa4e037a86d1877e98029ec9b/src/framework/core/op_plugins.cpp#L32)):*
> ```cpp
> {
>     for (int idx = 0; idx < argc - 1; idx++) {
>         if (strcmp(argv[idx], "--modules.plugins.path") == 0
> ```

The configuration file framework parses the command line for you.  You don't need to do it yourself. Specifically, `op_config_get_param` will retrieve options from both the configuration file and the command line with the command line taking precedence.

**Review by abelov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/324)* status: 7 of 10 files reviewed, 5 unresolved discussions (waiting on @DerangedMonkeyNinja)

___
*[src/framework/core/op_init.c, line 74 at r3](https://reviewable.io/reviews/spirent/openperf/324#-MGPpVrY4LQLkS3GjmSj:-MGaiIh-1K2H5IVdctc-:b-ecnih1) ([raw file](https://github.com/spirent/openperf/blob/a8f30781fcf5e2bfa4e037a86d1877e98029ec9b/src/framework/core/op_init.c#L74)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Using the comments below will allow you to revert the signature change here.
</blockquote></details>

Parameters are still required to get path to the openperf executable
___
*[src/framework/core/op_modules.c, line 33 at r3](https://reviewable.io/reviews/spirent/openperf/324#-MGPo-fy46OVhGpHlhp9:-MGaZVwS3rp7Z3qFxGaC:bu66n2k) ([raw file](https://github.com/spirent/openperf/blob/a8f30781fcf5e2bfa4e037a86d1877e98029ec9b/src/framework/core/op_modules.c#L33)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

I didn't notice this before...  What's the rationale for this length?
</blockquote></details>

I think some length, which does not fit into log line
___
*[src/framework/core/op_plugins.cpp, line 18 at r3](https://reviewable.io/reviews/spirent/openperf/324#-MGPom_S4Yq5_KTbxGzO:-MGaXZxVAoR4DzQDMTpG:b-clg2y1) ([raw file](https://github.com/spirent/openperf/blob/a8f30781fcf5e2bfa4e037a86d1877e98029ec9b/src/framework/core/op_plugins.cpp#L18)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Prefer you use `getcwd` for the working path name.
</blockquote></details>

getcwd returns current working directory. But here openperf executable path is required 
___
*[src/framework/core/op_plugins.cpp, line 20 at r3](https://reviewable.io/reviews/spirent/openperf/324#-MGPp3NYDtNwKn_Etr54:-MGaYVgi1E4COd6rvhLb:b-a4i58b) ([raw file](https://github.com/spirent/openperf/blob/a8f30781fcf5e2bfa4e037a86d1877e98029ec9b/src/framework/core/op_plugins.cpp#L20)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Not sure I understand this...  You're looking for plugins in a parent directory?
</blockquote></details>

Yes. I am expecting such default structure of openperf directory:
- bin
- - openperf
- plugins
- - plugin1.so
- - plugin2.so
___
*[src/framework/core/op_plugins.cpp, line 32 at r3](https://reviewable.io/reviews/spirent/openperf/324#-MGPoVDp67PfxwMXdjVs:-MGaiI101i9SsiQJm7oO:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/a8f30781fcf5e2bfa4e037a86d1877e98029ec9b/src/framework/core/op_plugins.cpp#L32)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

The configuration file framework parses the command line for you.  You don't need to do it yourself. Specifically, `op_config_get_param` will retrieve options from both the configuration file and the command line with the command line taking precedence.
</blockquote></details>

Done.

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/324)* status: all files reviewed, 1 unresolved discussion (waiting on @abelov-spirent)

___
*[src/framework/core/op_init.c, line 74 at r3](https://reviewable.io/reviews/spirent/openperf/324#-MGPpVrY4LQLkS3GjmSj:-MGivAdxCp3GcH3gZ8J1:bf6rp7e) ([raw file](https://github.com/spirent/openperf/blob/a8f30781fcf5e2bfa4e037a86d1877e98029ec9b/src/framework/core/op_init.c#L74)):*
<details><summary><i>Previously, abelov-spirent (Artem Belov) wrote…</i></summary><blockquote>

Parameters are still required to get path to the openperf executable
</blockquote></details>

Ok.  But if only the first argument is required, then just past that and not all of the other command line arguments.
___
*[src/framework/core/op_plugins.cpp, line 20 at r3](https://reviewable.io/reviews/spirent/openperf/324#-MGPp3NYDtNwKn_Etr54:-MGivRuj7Kp8BgVdoPTQ:b-cjjwpd) ([raw file](https://github.com/spirent/openperf/blob/a8f30781fcf5e2bfa4e037a86d1877e98029ec9b/src/framework/core/op_plugins.cpp#L20)):*
<details><summary><i>Previously, abelov-spirent (Artem Belov) wrote…</i></summary><blockquote>

Yes. I am expecting such default structure of openperf directory:
- bin
- - openperf
- plugins
- - plugin1.so
- - plugin2.so
</blockquote></details>

That seems like an unreasonable assumption. Just force the user to specify a path and drop this relative path search.

**Review by abelov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/324)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

___
*[src/framework/core/op_plugins.cpp, line 20 at r3](https://reviewable.io/reviews/spirent/openperf/324#-MGPp3NYDtNwKn_Etr54:-MGnlAfHCvvYeqDx8UVH:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/a8f30781fcf5e2bfa4e037a86d1877e98029ec9b/src/framework/core/op_plugins.cpp#L20)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

That seems like an unreasonable assumption. Just force the user to specify a path and drop this relative path search.
</blockquote></details>

Done.

**Review by DerangedMonkeyNinja — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/324#-:-MGyoBg-AV--6OLJofmM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
