### PR TITLE
Add {time,load}_scale to TVLP

### PR DESCRIPTION
**Pull request by loskutnikov-spirent**
Add properties to TVLP API for implementing the functionality of #355 issue.

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/360)

### CODE REVIEW

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/360)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja and @loskutnikov-spirent)

___
*[api/schema/v1/modules/tvlp.yaml, line 184 at r1](https://reviewable.io/reviews/spirent/openperf/360#-MKpP4oh6rv1AX2OOpG-:-MKpP4oh6rv1AX2OOpG0:brkl63q) ([raw file](https://github.com/spirent/openperf/blob/9d36f4e106880228f357fe8390cc786447269ed2/api/schema/v1/modules/tvlp.yaml#L184)):*
> ```YAML
>         exclusiveMinimum: true
>       time_scale:
>         type: integer
> ```

Why limit this scaling to an integer value? Also, why not let users speed up playback by using a value < 1?

**Review by loskutnikov-spirent — COMMENTED** [review]
> Reviewed 34 of 42 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/360)* status: all files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

___
*[api/schema/v1/modules/tvlp.yaml, line 184 at r1](https://reviewable.io/reviews/spirent/openperf/360#-MKpP4oh6rv1AX2OOpG-:-ML8XkBYDz-Zr1LReKF3:b-n8jt5p) ([raw file](https://github.com/spirent/openperf/blob/9d36f4e106880228f357fe8390cc786447269ed2/api/schema/v1/modules/tvlp.yaml#L184)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Why limit this scaling to an integer value? Also, why not let users speed up playback by using a value < 1?
</blockquote></details>

Changed to `double`

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/360)* status: all files reviewed, 2 unresolved discussions (waiting on @loskutnikov-spirent)

___
*[src/modules/tvlp/api_converters.cpp, line 32 at r3](https://reviewable.io/reviews/spirent/openperf/360#-MLPHFLSDjPAkIEBD804:-MLPHFLSDjPAkIEBD805:b-lbt5u9) ([raw file](https://github.com/spirent/openperf/blob/189424bda167169d57503a53165f34664f1cf535/src/modules/tvlp/api_converters.cpp#L32)):*
> ```cpp
>     double seconds = 0;
>     sscanf(date.c_str(), "%d-%d-%dT%d:%d:%lfZ", &d, &d, &d, &d, &d, &seconds);
>     dur += std::chrono::nanoseconds(static_cast<long>(std::nano::den * seconds)
> ```

You shouldn't need to do any manual casting or converting when using std::chrono.
___
*[src/modules/tvlp/controller.cpp, line 26 at r3](https://reviewable.io/reviews/spirent/openperf/360#-MLPI0H48CsUyGKJCxOl:-MLPI0H48CsUyGKJCxOm:b-s4sl1b) ([raw file](https://github.com/spirent/openperf/blob/189424bda167169d57503a53165f34664f1cf535/src/modules/tvlp/controller.cpp#L26)):*
> ```cpp
>     auto scale_length = [](model::tvlp_module_profile_t& profiles) {
>         duration total_length = 0ms;
>         for (auto& p : profiles) {
> ```

const?

**Review by loskutnikov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/360)* status: 37 of 39 files reviewed, 2 unresolved discussions (waiting on @DerangedMonkeyNinja and @loskutnikov-spirent)

___
*[src/modules/tvlp/api_converters.cpp, line 32 at r3](https://reviewable.io/reviews/spirent/openperf/360#-MLPHFLSDjPAkIEBD804:-MLR2wBy8mJ6ILMnRH_m:b6x0geu) ([raw file](https://github.com/spirent/openperf/blob/189424bda167169d57503a53165f34664f1cf535/src/modules/tvlp/api_converters.cpp#L32)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

You shouldn't need to do any manual casting or converting when using std::chrono.
</blockquote></details>

This code cuts off nanoseconds from the double representation of seconds. There is no standard way or conversion for this purpose. Afraid, I don't understand clearly what you want.

FYI: This code is not mine at all and was approved early. I only moved it from `* .h` to` * .cpp` file.
___
*[src/modules/tvlp/controller.cpp, line 26 at r3](https://reviewable.io/reviews/spirent/openperf/360#-MLPI0H48CsUyGKJCxOl:-MLR2bpR3R89MXqktyLs:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/189424bda167169d57503a53165f34664f1cf535/src/modules/tvlp/controller.cpp#L26)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

const?
</blockquote></details>

Done.

**Review by DerangedMonkeyNinja — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/360#-:-MLSpLv71SZQzJ_ZJtTX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by DerangedMonkeyNinja — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/360#-:-MLhC0GI5lZ1O5slNRT4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @loskutnikov-spirent)

**Pull request merged**
