### PR TITLE
Cpu generator rewrite

### PR DESCRIPTION
**Pull request by DerangedMonkeyNinja**
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/538)

### CODE REVIEW

**Review by dmortondev — CHANGES_REQUESTED** [review]
> Reviewed 88 of 88 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/538)* status: all files reviewed, 6 unresolved discussions (waiting on @DerangedMonkeyNinja)

___
*[src/framework/generator/v2/pid_controller.hpp, line 195 at r1](https://reviewable.io/reviews/spirent/openperf/538#-MoeAJ4_6CcfCjSRQRQU:-MoeAJ4_6CcfCjSRQRQV:blghftt) ([raw file](https://github.com/spirent/openperf/blob/7cbacf6df5f43e22c98de05d04ddce779c593deb/src/framework/generator/v2/pid_controller.hpp#L195)):*
> ```cpp
>         last_y_ = stop.value;
> 
>         // OP_LOG(OP_LOG_TRACE,
> ```

Nit: uncomment or take out?
___
*[src/framework/generator/v2/worker_client.tcc, line 83 at r1](https://reviewable.io/reviews/spirent/openperf/538#-MoeC2xR0Xh3756s-L5Y:-MoeC2xS7Q9TznQh7XXs:b-40o9fr) ([raw file](https://github.com/spirent/openperf/blob/7cbacf6df5f43e22c98de05d04ddce779c593deb/src/framework/generator/v2/worker_client.tcc#L83)):*
> ```cpp
>         &sync,
>         nb_workers,
>         1000,
> ```

Nit: Magic number? To me a comment would be great.
___
*[src/framework/generator/v2/worker_client.tcc, line 107 at r1](https://reviewable.io/reviews/spirent/openperf/538#-MoeCFmx68zG7hhwfgVV:-MoeCFmx68zG7hhwfgVW:b2nreh6) ([raw file](https://github.com/spirent/openperf/blob/7cbacf6df5f43e22c98de05d04ddce779c593deb/src/framework/generator/v2/worker_client.tcc#L107)):*
> ```cpp
>         &sync,
>         nb_workers,
>         1000,
> ```

Same as above.
___
*[src/modules/cpu/cpu_transmogrify.cpp, line 384 at r1](https://reviewable.io/reviews/spirent/openperf/538#-MoeJc-m6dTo1gTr4-2G:-MoeJc-m6dTo1gTr4-2H:b-cyr6cm) ([raw file](https://github.com/spirent/openperf/blob/7cbacf6df5f43e22c98de05d04ddce779c593deb/src/modules/cpu/cpu_transmogrify.cpp#L384)):*
> ```cpp
>                    [](const auto& t) { return (to_swagger(t)); });
> 
> #if 0
> ```

Minor: should this be if'ed out?
___
*[src/modules/cpu/generator/coordinator.cpp, line 170 at r1](https://reviewable.io/reviews/spirent/openperf/538#-MoeLvDg09C33_Bg7m9l:-MoeLvDg09C33_Bg7m9m:b2rcfk) ([raw file](https://github.com/spirent/openperf/blob/7cbacf6df5f43e22c98de05d04ddce779c593deb/src/modules/cpu/generator/coordinator.cpp#L170)):*
> ```cpp
> 
>     return (0);
>     // return (std::nullopt);
> ```

Nit: dead code?
___
*[src/modules/cpu/generator/coordinator.cpp, line 342 at r1](https://reviewable.io/reviews/spirent/openperf/538#-MoeM74J2Co8AKdz472R:-MoeM74J2Co8AKdz472S:bx1m7rk) ([raw file](https://github.com/spirent/openperf/blob/7cbacf6df5f43e22c98de05d04ddce779c593deb/src/modules/cpu/generator/coordinator.cpp#L342)):*
> ```cpp
>     m_prev_sum = sum;
> 
>     // OP_LOG(OP_LOG_TRACE,
> ```

Nit: Dead code?

**Review by DerangedMonkeyNinja — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/538)* status: 84 of 88 files reviewed, 1 unresolved discussion (waiting on @dmortondev)

___
*[src/framework/generator/v2/pid_controller.hpp, line 195 at r1](https://reviewable.io/reviews/spirent/openperf/538#-MoeAJ4_6CcfCjSRQRQU:-MoihXh23PMQXqiyZmju:b2w1hcr) ([raw file](https://github.com/spirent/openperf/blob/7cbacf6df5f43e22c98de05d04ddce779c593deb/src/framework/generator/v2/pid_controller.hpp#L195)):*
<details><summary><i>Previously, dmortondev (Dan Morton) wrote…</i></summary><blockquote>

Nit: uncomment or take out?
</blockquote></details>

Intentionally commented actually...  It's helpful to look at the debug output when tweaking PID values, but normally not needed, hence commented out. I want to keep it there for future reference.
___
*[src/framework/generator/v2/worker_client.tcc, line 107 at r1](https://reviewable.io/reviews/spirent/openperf/538#-MoeCFmx68zG7hhwfgVV:-MoihsDoAVmO-MvdgmH2:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/7cbacf6df5f43e22c98de05d04ddce779c593deb/src/framework/generator/v2/worker_client.tcc#L107)):*
<details><summary><i>Previously, dmortondev (Dan Morton) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

**Review by dmortondev — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/538#-:-Moj7Zmc8a0D3w8rd6oK:bg7igkv)* status: 84 of 88 files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja and @dmortondev)

___
*[src/framework/generator/v2/pid_controller.hpp, line 195 at r1](https://reviewable.io/reviews/spirent/openperf/538#-MoeAJ4_6CcfCjSRQRQU:-Moj7SRv1yPrdrqhs0Gx:b2h0gno) ([raw file](https://github.com/spirent/openperf/blob/7cbacf6df5f43e22c98de05d04ddce779c593deb/src/framework/generator/v2/pid_controller.hpp#L195)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Intentionally commented actually...  It's helpful to look at the debug output when tweaking PID values, but normally not needed, hence commented out. I want to keep it there for future reference.
</blockquote></details>

OK sounds good.
___
*[src/framework/generator/v2/worker_client.tcc, line 107 at r1](https://reviewable.io/reviews/spirent/openperf/538#-MoeCFmx68zG7hhwfgVV:-Moj7U_7BHkurBuXo6y-:b4c9lyr) ([raw file](https://github.com/spirent/openperf/blob/7cbacf6df5f43e22c98de05d04ddce779c593deb/src/framework/generator/v2/worker_client.tcc#L107)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:thumbsup:

**Review by DerangedMonkeyNinja — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/538)* status: 84 of 88 files reviewed, 1 unresolved discussion (waiting on @dmortondev)

___
*[src/framework/generator/v2/worker_client.tcc, line 107 at r1](https://reviewable.io/reviews/spirent/openperf/538#-MoeCFmx68zG7hhwfgVV:-MojMkzDDWX7oGeh3kL-:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/7cbacf6df5f43e22c98de05d04ddce779c593deb/src/framework/generator/v2/worker_client.tcc#L107)):*
<details><summary><i>Previously, dmortondev (Dan Morton) wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

Done.

**Pull request merged**
