### PR TITLE
CPU PID Control

### LINKED ISSUE #309: No pid control in any of the generators
For example, it's how the CPU load generator knows to back down when other generators are using CPU load.

### PR DESCRIPTION
**Pull request by loskutnikov-spirent**
CPU Generator system load mode with PID control.
Closes #309.

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/349)

### CODE REVIEW

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/349)* status: all files reviewed, 1 unresolved discussion (waiting on @loskutnikov-spirent)

*[a discussion](https://reviewable.io/reviews/spirent/openperf/349#-MJTiSNgCK8P3sOHZ_pc:-MJTiSNgCK8P3sOHZ_pd:b8f3cnh) (no related file):*
The code looks ok. I'd like to see an AAT that covers the system CPU load, though.

---

**Review by loskutnikov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/349)* status: 8 of 24 files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

*[a discussion](https://reviewable.io/reviews/spirent/openperf/349#-MJTiSNgCK8P3sOHZ_pc:-MJX5UUWBs-mdgkIOW-r:b-4vggrz) (no related file):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

The code looks ok. I'd like to see an AAT that covers the system CPU load, though.
</blockquote></details>

Added AAT tests for the system CPU load. Updated the CPU module documentation.

---

**Review by DerangedMonkeyNinja — COMMENTED** [review]
> Reviewed 3 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/349)* status: 11 of 24 files reviewed, all discussions resolved

**Review by DerangedMonkeyNinja — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/349#-:-MJgMLIm8bo-9ynB5fQR:bnfp4nl)* status: 11 of 24 files reviewed, all discussions resolved

**Pull request merged**
