### PR TITLE
Add target utilization time field to CPU Generator statistics

### LINKED ISSUE #406: Requesting CpuGeneratorResult to provide intended CPU time
When you create a CPU config, you provide a target utilization, however that target or intended value isn't present in the results.  I'm also requesting this value be represented as the same unit type as the available and utilization values that are returned so that we can use it within dynamic results t-digest configs.

### PR DESCRIPTION
**Pull request by loskutnikov-spirent**
Closes #406

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/412)

### CODE REVIEW

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 7 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/412)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja and @loskutnikov-spirent)

*[a discussion](https://reviewable.io/reviews/spirent/openperf/412#-MNyxhro31JlSYneinxJ:-MNyxhro31JlSYneinxK:b-agaiay) (no related file):*
Can you add a function to `tests/aat/common/matcher/cpu.py` to sanity check the generated CPU stats, e.g. all expected values are present and error = target - utilization? I was surprised to see that there is no function currently doing that, but there should be!

---

**Review by DerangedMonkeyNinja — COMMENTED** [review]
> Reviewed 8 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/412)* status: all files reviewed, 1 unresolved discussion (waiting on @loskutnikov-spirent)

**Review by loskutnikov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/412)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

*[a discussion](https://reviewable.io/reviews/spirent/openperf/412#-MNyxhro31JlSYneinxJ:-MO-_0ydE2YNhDsIzShy:blm80pe) (no related file):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Can you add a function to `tests/aat/common/matcher/cpu.py` to sanity check the generated CPU stats, e.g. all expected values are present and error = target - utilization? I was surprised to see that there is no function currently doing that, but there should be!
</blockquote></details>

Added checks for `error` and `utilization` values.

---

**Review by DerangedMonkeyNinja — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/412#-:-MOIJGZ2EcY3iZzHiOoR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @loskutnikov-spirent)

**Pull request merged**
