### PR TITLE
CPU Generator system load mode

### LINKED ISSUE #343: Add the System load capability for CPU Generator
Add additional top-level field into CPU Generator configuration to specify the overall system load, instead of per core load.
This field will be named `utilization` object. 
User should use only one of `utilization` or `cores` fields in configuration.

When `utilization` value is specified, OpenPerf creates one thread to each available CPU core and apply this value to them. 
For system load mode will be used `scalar` instruction set.

### PR DESCRIPTION
**Pull request by loskutnikov-spirent**
Resolves #343

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/346)

### CODE REVIEW

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/346)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja and @loskutnikov-spirent)

___
*[api/schema/v1/modules/cpu.yaml, line 330 at r1](https://reviewable.io/reviews/spirent/openperf/346#-MI_SIQNCtV4aBl6oPjH:-MI_SIQNCtV4aBl6oPjI:b-wub2mz) ([raw file](https://github.com/spirent/openperf/blob/6c1585d4c11e64ca03c55230bd7a749b601937fb/api/schema/v1/modules/cpu.yaml#L330)):*
> ```YAML
>     description: CPU Generator Configuration
>     properties:
>       utilization:
> ```

This change seems like a lot of complexity to help the client do some division. I'd prefer the client just be explicit about what they want then to have these two modes of configurations.

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/346)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @loskutnikov-spirent)

___
*[api/schema/v1/modules/cpu.yaml, line 330 at r1](https://reviewable.io/reviews/spirent/openperf/346#-MI_SIQNCtV4aBl6oPjH:-MIb-EYn676kChPZfvPL:bfcsdwd) ([raw file](https://github.com/spirent/openperf/blob/6c1585d4c11e64ca03c55230bd7a749b601937fb/api/schema/v1/modules/cpu.yaml#L330)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

This change seems like a lot of complexity to help the client do some division. I'd prefer the client just be explicit about what they want then to have these two modes of configurations.
</blockquote></details>

Since utilization will behave significantly differently than the per-core configuration, this configuration objection should have an enum 'method' property that allows explicit configuration of one of the two methods and provides two configuration sub-objects; one for each configuration method type.

This pattern is used repeatedly in the packetio.yaml file, so you can see examples there.

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 2 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/346)* status: 4 of 14 files reviewed, 2 unresolved discussions (waiting on @DerangedMonkeyNinja and @loskutnikov-spirent)

___
*[api/schema/v1/modules/cpu.yaml, line 347 at r2](https://reviewable.io/reviews/spirent/openperf/346#-MIfzwNNBsVolOn3OsdF:-MIfzwNNBsVolOn3OsdG:b-5r66wv) ([raw file](https://github.com/spirent/openperf/blob/453576a93996cf5a7810f6fb20e2508aa1fe715c/api/schema/v1/modules/cpu.yaml#L347)):*
> ```YAML
>             minimum: 0
>             exclusiveMinimum: true
>             maximum: 100
> ```

Shouldn't the maximum here be 100 * the number of available cores?

**Review by loskutnikov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/346)* status: 4 of 14 files reviewed, 2 unresolved discussions (waiting on @DerangedMonkeyNinja)

___
*[api/schema/v1/modules/cpu.yaml, line 330 at r1](https://reviewable.io/reviews/spirent/openperf/346#-MI_SIQNCtV4aBl6oPjH:-MIgUvTY75gseZeTr1t_:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/6c1585d4c11e64ca03c55230bd7a749b601937fb/api/schema/v1/modules/cpu.yaml#L330)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Since utilization will behave significantly differently than the per-core configuration, this configuration objection should have an enum 'method' property that allows explicit configuration of one of the two methods and provides two configuration sub-objects; one for each configuration method type.

This pattern is used repeatedly in the packetio.yaml file, so you can see examples there.
</blockquote></details>

Done.
___
*[api/schema/v1/modules/cpu.yaml, line 347 at r2](https://reviewable.io/reviews/spirent/openperf/346#-MIfzwNNBsVolOn3OsdF:-MIgUwSV8eM91vGVZtZb:baohk1l) ([raw file](https://github.com/spirent/openperf/blob/453576a93996cf5a7810f6fb20e2508aa1fe715c/api/schema/v1/modules/cpu.yaml#L347)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Shouldn't the maximum here be 100 * the number of available cores?
</blockquote></details>

I tried to figure out here: https://github.com/Spirent/openperf/issues/343#issuecomment-701933246

**Review by loskutnikov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/346)* status: 1 of 15 files reviewed, 2 unresolved discussions (waiting on @DerangedMonkeyNinja and @jhiga)

___
*[api/schema/v1/modules/cpu.yaml, line 347 at r2](https://reviewable.io/reviews/spirent/openperf/346#-MIfzwNNBsVolOn3OsdF:-MIiVY723F5Zlkdt5mig:bnl36su) ([raw file](https://github.com/spirent/openperf/blob/453576a93996cf5a7810f6fb20e2508aa1fe715c/api/schema/v1/modules/cpu.yaml#L347)):*
<details><summary><i>Previously, loskutnikov-spirent (Anatoly Loskutnikov) wrote…</i></summary><blockquote>

I tried to figure out here: https://github.com/Spirent/openperf/issues/343#issuecomment-701933246
</blockquote></details>

Because you and @jhiga prefer the second variant, I changed the maximum value of utilization to `100 * cores_number`.

**Review by DerangedMonkeyNinja — APPROVED** [review]
:lgtm:

> Reviewed 3 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/346#-:-MIuZGNJ5lsZLx39kawL:bnfp4nl)* status: 4 of 15 files reviewed, all discussions resolved (waiting on @DerangedMonkeyNinja)

**Pull request merged**
