### PR TITLE
Add analyzer flow digests

### PR DESCRIPTION
**Pull request by DerangedMonkeyNinja**
These digests store k-means clusters of analyzer flow counters to allow clients to generate Cumulative Distribution Functions (CDFs) or Probability Density Functions (PDFs) for them. The implementation is based off of digestible and provided by a new library, regurgitate.  Regurgitate is vectorized and compiled by ISPC. Additionally, run-time benchmarking ensures that the fastest vectorized implementation is chosen for the host platform.

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/492)

### CODE REVIEW

**Review by djoyner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/492)* status: 0 of 92 files reviewed, 1 unresolved discussion (waiting on @cmyers-spirent, @DerangedMonkeyNinja, and @dmorton-spirent)

___
*[src/lib/regurgitate/ispc/impl/bitonic_centroid_sort_x16.h, line 657 at r1](https://reviewable.io/reviews/spirent/openperf/492#-Ma-ktXB5BZzczesU6_i:-Ma-ktXB5BZzczesU6_j:bygrbei) ([raw file](https://github.com/spirent/openperf/blob/92ba5d0d0ef24d297904e5ffe27cc37d5b35355e/src/lib/regurgitate/ispc/impl/bitonic_centroid_sort_x16.h#L657)):*
> ```objc
> #endif
> 
> #endif /* _REGURGITATE_IMPL_BITONIC_CENTROID_SORT_X16_H_ */
> ```

Ok, I've just gotta ask... did you write this completely by hand or auto-generate portions?

**Review by DerangedMonkeyNinja — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/492)* status: 0 of 92 files reviewed, 1 unresolved discussion (waiting on @cmyers-spirent, @djoyner, and @dmorton-spirent)

___
*[src/lib/regurgitate/ispc/impl/bitonic_centroid_sort_x16.h, line 657 at r1](https://reviewable.io/reviews/spirent/openperf/492#-Ma-ktXB5BZzczesU6_i:-Ma-mR7VBBkorUY6IgAM:b-6wlzu4) ([raw file](https://github.com/spirent/openperf/blob/92ba5d0d0ef24d297904e5ffe27cc37d5b35355e/src/lib/regurgitate/ispc/impl/bitonic_centroid_sort_x16.h#L657)):*
<details><summary><i>Previously, djoyner (David Joyner) wrote…</i></summary><blockquote>

Ok, I've just gotta ask... did you write this completely by hand or auto-generate portions?
</blockquote></details>

If you don't count cut/paste...  by hand. The comments in the transpose function are there so I could figure out the correct mask as I went. The masks in the merge function and the ordering in the sorting function are based on well-known solutions to merging/sorting 16-way networks. Since I only had to do this once, I just wrote it all out.

**Review by cmyers-spirent — APPROVED** [review]
> Reviewed 92 of 92 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/492)* status: all files reviewed, 2 unresolved discussions (waiting on @DerangedMonkeyNinja, @djoyner, and @dmorton-spirent)

___
*[src/lib/regurgitate/instruction_set.hpp, line 1 at r1](https://reviewable.io/reviews/spirent/openperf/492#-Ma2ejE230fIl52ccN8C:-Ma2ejE230fIl52ccN8D:blv1nqr) ([raw file](https://github.com/spirent/openperf/blob/92ba5d0d0ef24d297904e5ffe27cc37d5b35355e/src/lib/regurgitate/instruction_set.hpp#L1)):*
> ```cpp
> #ifndef _LIB_REGURGITATE_INSTRUCTION_SET_HPP_
> ```

Seems like we already have a few files like this.  one in lib/spirent_pga and one in modules/cpu.
Would it be possible to consolidate the instruction_set*.* files?

**Review by DerangedMonkeyNinja — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/492)* status: 88 of 93 files reviewed, 1 unresolved discussion (waiting on @cmyers-spirent, @djoyner, and @dmorton-spirent)

___
*[src/lib/regurgitate/instruction_set.hpp, line 1 at r1](https://reviewable.io/reviews/spirent/openperf/492#-Ma2ejE230fIl52ccN8C:-MaBuJeg5bdxLHR3DwkY:b-mpjhv4) ([raw file](https://github.com/spirent/openperf/blob/92ba5d0d0ef24d297904e5ffe27cc37d5b35355e/src/lib/regurgitate/instruction_set.hpp#L1)):*
<details><summary><i>Previously, cmyers-spirent wrote…</i></summary><blockquote>

Seems like we already have a few files like this.  one in lib/spirent_pga and one in modules/cpu.
Would it be possible to consolidate the instruction_set*.* files?

</blockquote></details>

It would be ;-p

My thinking for the lib/* is that I'd like these modules to be totally self contained so they can actually be used as libraries in the future if needed. Currently, their only real dependency is on the makefile infrastructure  and ISPC to build them.

I definitely wouldn't mind consolidating these files in the future though.
___
*[src/lib/regurgitate/ispc/impl/bitonic_centroid_sort_x16.h, line 657 at r1](https://reviewable.io/reviews/spirent/openperf/492#-Ma-ktXB5BZzczesU6_i:-MaBuqzr6yL1UOFU81v4:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/92ba5d0d0ef24d297904e5ffe27cc37d5b35355e/src/lib/regurgitate/ispc/impl/bitonic_centroid_sort_x16.h#L657)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

If you don't count cut/paste...  by hand. The comments in the transpose function are there so I could figure out the correct mask as I went. The masks in the merge function and the ordering in the sorting function are based on well-known solutions to merging/sorting 16-way networks. Since I only had to do this once, I just wrote it all out.
</blockquote></details>

Done.

**Review by cmyers-spirent — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/492)* status: all files reviewed, 1 unresolved discussion (waiting on @djoyner and @dmorton-spirent)

**Review by dmorton-spirent — APPROVED** [review]
> Reviewed 63 of 92 files at r1, 2 of 5 files at r2, 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/492)* status: 92 of 93 files reviewed, 2 unresolved discussions (waiting on @cmyers-spirent, @DerangedMonkeyNinja, and @djoyner)

___
*[api/schema/v1/modules/packet/analyzer.yaml, line 487 at r3](https://reviewable.io/reviews/spirent/openperf/492#-MaUlsa3B1qiz6beRfFU:-MaUlsa3B1qiz6beRfFV:bo4ifba) ([raw file](https://github.com/spirent/openperf/blob/74fd83c9d008a64e6f85914f599e93f96e7fa491/api/schema/v1/modules/packet/analyzer.yaml#L487)):*
> ```YAML
>           List of result digests to generate per flow for received packets.
>           Sequence run length, latency, and jitter digests require Spirent
>           signatures in the received packets.
> ```

Would it be worth putting in a warning here about potential performance impacts of enabling this feature? Or if not here in the markdown documentation?

**Review by DerangedMonkeyNinja — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/492)* status: 92 of 93 files reviewed, 2 unresolved discussions (waiting on @cmyers-spirent, @djoyner, and @dmorton-spirent)

___
*[api/schema/v1/modules/packet/analyzer.yaml, line 487 at r3](https://reviewable.io/reviews/spirent/openperf/492#-MaUlsa3B1qiz6beRfFU:-MaV3vrf3vtx279fJ1uR:b-s8mlac) ([raw file](https://github.com/spirent/openperf/blob/74fd83c9d008a64e6f85914f599e93f96e7fa491/api/schema/v1/modules/packet/analyzer.yaml#L487)):*
<details><summary><i>Previously, dmorton-spirent (Dan Morton) wrote…</i></summary><blockquote>

Would it be worth putting in a warning here about potential performance impacts of enabling this feature? Or if not here in the markdown documentation?
</blockquote></details>

Probably worthwhile to have a dedicated document for that. Every result option you add slows things down, but knowing the relative cost would probably be helpful.

**Review by dmorton-spirent — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/492#-:-MaVOgUVDXaq8QkC4TNp:bg7igkv)* status: 92 of 93 files reviewed, 1 unresolved discussion (waiting on @cmyers-spirent and @djoyner)

**Pull request merged**
