### PR TITLE
Network Modules performance fix

### PR DESCRIPTION
**Pull request by abelov-spirent**
- Fix UDP and TCP performance issue. O_NONBLOCK cause huge performance drop.
- Fix firehose protocol

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/436)

### CODE REVIEW

**Review by cmyers-spirent — COMMENTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/436)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @abelov-spirent and @DerangedMonkeyNinja)

___
*[src/modules/network/firehose/server_tcp.cpp, line 86 at r1](https://reviewable.io/reviews/spirent/openperf/436#-MPglefT0qd4iwiPK-r9:-MPglefT0qd4iwiPK-rA:b-6ra15n) ([raw file](https://github.com/spirent/openperf/blob/7b7a6113ce6155377cfd02b7d604b1e041d8f9f8/src/modules/network/firehose/server_tcp.cpp#L86)):*
> ```cpp
>         return tl::make_unexpected<std::string>(strerror(err));
>     }
> ```

Why is the SO_REUSEPORT option being removed?
___
*[src/modules/network/firehose/server_tcp.cpp, line 147 at r1](https://reviewable.io/reviews/spirent/openperf/436#-MPgwA7b2IDDvXjwoJVI:-MPgwA7b2IDDvXjwoJVJ:bh8mapm) ([raw file](https://github.com/spirent/openperf/blob/2bbc4a65edf97035560631d5e58f9c515d3fe556/src/modules/network/firehose/server_tcp.cpp#L147)):*
> ```cpp
> {
>     m_stopped.store(true, std::memory_order_relaxed);
> ```

This may not be thread-safe and could cause issues.  Is it really necessary?
Since you use SO_RECVTIMO, the thread should eventually exit when m_stopped =true.
___
*[src/modules/network/firehose/server_tcp.cpp, line 279 at r1](https://reviewable.io/reviews/spirent/openperf/436#-MPgyOC77QAcjW4C8ydR:-MPgyOC77QAcjW4C8ydS:b-ty0qlu) ([raw file](https://github.com/spirent/openperf/blob/2bbc4a65edf97035560631d5e58f9c515d3fe556/src/modules/network/firehose/server_tcp.cpp#L279)):*
> ```cpp
>                 m_stat.connections++;
>             }
> ```

When processing multiple connections, using SO_RCVTIMEO on each socket it will impact performance if one connection has data and the other does not.

It would be better to use poll/epoll/select, but seems dpdk socket interface doesn't support that...

Is it common to have multiple connections?

**Review by abelov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/436)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @cmyers-spirent and @DerangedMonkeyNinja)

___
*[src/modules/network/firehose/server_tcp.cpp, line 86 at r1](https://reviewable.io/reviews/spirent/openperf/436#-MPglefT0qd4iwiPK-r9:-MPhm553BQuoJC7got2j:b-clafm9) ([raw file](https://github.com/spirent/openperf/blob/7b7a6113ce6155377cfd02b7d604b1e041d8f9f8/src/modules/network/firehose/server_tcp.cpp#L86)):*
<details><summary><i>Previously, cmyers-spirent wrote…</i></summary><blockquote>

Why is the SO_REUSEPORT option being removed?
</blockquote></details>

Accept thread is separate from workers so REUSEPORT is does not require in OpenPerf and may cause an issues
___
*[src/modules/network/firehose/server_tcp.cpp, line 147 at r1](https://reviewable.io/reviews/spirent/openperf/436#-MPgwA7b2IDDvXjwoJVI:-MPhmUAL24Qid4fVaFq_:b-2lvacv) ([raw file](https://github.com/spirent/openperf/blob/2bbc4a65edf97035560631d5e58f9c515d3fe556/src/modules/network/firehose/server_tcp.cpp#L147)):*
<details><summary><i>Previously, cmyers-spirent wrote…</i></summary><blockquote>

This may not be thread-safe and could cause issues.  Is it really necessary?
Since you use SO_RECVTIMO, the thread should eventually exit when m_stopped =true.

</blockquote></details>

It is required to avoid block on write operations. Atomic here should guarantee of thread safety
___
*[src/modules/network/firehose/server_tcp.cpp, line 279 at r1](https://reviewable.io/reviews/spirent/openperf/436#-MPgyOC77QAcjW4C8ydR:-MPhmwwDDSUqo4avCfCj:bhqu7ps) ([raw file](https://github.com/spirent/openperf/blob/2bbc4a65edf97035560631d5e58f9c515d3fe556/src/modules/network/firehose/server_tcp.cpp#L279)):*
<details><summary><i>Previously, cmyers-spirent wrote…</i></summary><blockquote>

When processing multiple connections, using SO_RCVTIMEO on each socket it will impact performance if one connection has data and the other does not.

It would be better to use poll/epoll/select, but seems dpdk socket interface doesn't support that...

Is it common to have multiple connections?
</blockquote></details>

Yes, it is common to have multiple connections. It gives much better performance than O_NONBLOCK.
DPDK does not support SO_RCVTIMEO anyway. And it has much better handling of O_NONBLOCK option. So it should be enouth.

**Review by cmyers-spirent — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/436)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @abelov-spirent, @cmyers-spirent, and @DerangedMonkeyNinja)

___
*[src/modules/network/firehose/server_tcp.cpp, line 147 at r1](https://reviewable.io/reviews/spirent/openperf/436#-MPgwA7b2IDDvXjwoJVI:-MPlcj_CEPgZOUcCZQyt:bml1uwx) ([raw file](https://github.com/spirent/openperf/blob/2bbc4a65edf97035560631d5e58f9c515d3fe556/src/modules/network/firehose/server_tcp.cpp#L147)):*
<details><summary><i>Previously, abelov-spirent (Artem Belov) wrote…</i></summary><blockquote>

It is required to avoid block on write operations. Atomic here should guarantee of thread safety
</blockquote></details>

The acquiring the fd is atomic, but as far as I can tell DPDK sockets will not support close while writing to it.

The socket  API client socket channels are not reference counted and it is using a unprotected hashtab in the channels_hashtab.hpp and that might have some thread safety issues as well.  Seems like the openperf socket module may need some work...

Are there any known stability issues with DPDK based sockets?
___
*[src/modules/network/firehose/server_tcp.cpp, line 279 at r1](https://reviewable.io/reviews/spirent/openperf/436#-MPgyOC77QAcjW4C8ydR:-MPljl3y96NuZuG47SVn:b1bk1do) ([raw file](https://github.com/spirent/openperf/blob/2bbc4a65edf97035560631d5e58f9c515d3fe556/src/modules/network/firehose/server_tcp.cpp#L279)):*
<details><summary><i>Previously, abelov-spirent (Artem Belov) wrote…</i></summary><blockquote>

Yes, it is common to have multiple connections. It gives much better performance than O_NONBLOCK.
DPDK does not support SO_RCVTIMEO anyway. And it has much better handling of O_NONBLOCK option. So it should be enouth.
</blockquote></details>

Hmmm.  I guess as long as all connections are receiving packets are the same rate, this should get reasonable performance.
We probably will need to switch to poll/epoll/select eventually.

**Review by abelov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/436)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @cmyers-spirent and @DerangedMonkeyNinja)

___
*[src/modules/network/firehose/server_tcp.cpp, line 147 at r1](https://reviewable.io/reviews/spirent/openperf/436#-MPgwA7b2IDDvXjwoJVI:-MPlpiqw0R_s7VsP37EN:bukzvhe) ([raw file](https://github.com/spirent/openperf/blob/2bbc4a65edf97035560631d5e58f9c515d3fe556/src/modules/network/firehose/server_tcp.cpp#L147)):*
<details><summary><i>Previously, cmyers-spirent wrote…</i></summary><blockquote>

The acquiring the fd is atomic, but as far as I can tell DPDK sockets will not support close while writing to it.

The socket  API client socket channels are not reference counted and it is using a unprotected hashtab in the channels_hashtab.hpp and that might have some thread safety issues as well.  Seems like the openperf socket module may need some work...

Are there any known stability issues with DPDK based sockets?
</blockquote></details>

O_NONBLOCK flag is used for dpdk driver, so close should not cause a stability issues. The easiest solution is to wait for worker thread stop and then to close sockets. Just for dpdk driver. What do you think?
___
*[src/modules/network/firehose/server_tcp.cpp, line 279 at r1](https://reviewable.io/reviews/spirent/openperf/436#-MPgyOC77QAcjW4C8ydR:-MPoHV98ApCJndlFQjni:b-nnecz8) ([raw file](https://github.com/spirent/openperf/blob/2bbc4a65edf97035560631d5e58f9c515d3fe556/src/modules/network/firehose/server_tcp.cpp#L279)):*
<details><summary><i>Previously, cmyers-spirent wrote…</i></summary><blockquote>

Hmmm.  I guess as long as all connections are receiving packets are the same rate, this should get reasonable performance.
We probably will need to switch to poll/epoll/select eventually.

</blockquote></details>

I have tested performance of network server and current timeout bring much less delay than poll mode for kernel driver

**Review by cmyers-spirent — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/436)* status: all files reviewed, 1 unresolved discussion (waiting on @abelov-spirent and @DerangedMonkeyNinja)

___
*[src/modules/network/firehose/server_tcp.cpp, line 147 at r1](https://reviewable.io/reviews/spirent/openperf/436#-MPgwA7b2IDDvXjwoJVI:-MPoryVHAdSyOf4Z_Ood:bgofl61) ([raw file](https://github.com/spirent/openperf/blob/2bbc4a65edf97035560631d5e58f9c515d3fe556/src/modules/network/firehose/server_tcp.cpp#L147)):*
<details><summary><i>Previously, abelov-spirent (Artem Belov) wrote…</i></summary><blockquote>

O_NONBLOCK flag is used for dpdk driver, so close should not cause a stability issues. The easiest solution is to wait for worker thread stop and then to close sockets. Just for dpdk driver. What do you think?
</blockquote></details>

Yeah I think it will be safer if dpdk driver mode is not able to perform socket operations on same fd from multiple threads.

**Review by abelov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/436)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @cmyers-spirent and @DerangedMonkeyNinja)

___
*[src/modules/network/firehose/server_tcp.cpp, line 147 at r1](https://reviewable.io/reviews/spirent/openperf/436#-MPgwA7b2IDDvXjwoJVI:-MPp7CZUErLJfVQzqpr5:bb6un1j) ([raw file](https://github.com/spirent/openperf/blob/2bbc4a65edf97035560631d5e58f9c515d3fe556/src/modules/network/firehose/server_tcp.cpp#L147)):*
<details><summary><i>Previously, cmyers-spirent wrote…</i></summary><blockquote>

Yeah I think it will be safer if dpdk driver mode is not able to perform socket operations on same fd from multiple threads.
</blockquote></details>

Done

**Review by cmyers-spirent — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/436)* status: all files reviewed, 1 unresolved discussion (waiting on @abelov-spirent and @DerangedMonkeyNinja)

___
*[src/modules/network/firehose/server_tcp.cpp, line 149 at r2](https://reviewable.io/reviews/spirent/openperf/436#-MPpI5zSA6-GWnYdT3gX:-MPpI5zSA6-GWnYdT3gY:b-iwgi6o) ([raw file](https://github.com/spirent/openperf/blob/8f6d74e26f173938d3cafc6e8c69ee2d8e6800e8/src/modules/network/firehose/server_tcp.cpp#L149)):*
> ```cpp
> 
>     // Closing blocked socket does not required for dpdk driver because of
>     // using SOCK_NONBLOCK flag
> ```

since checking it in multiple places now would help to have a  function in the driver to check if blocking  socket read/write should be used e.g.:

  m_driver->needs_blocking_sockets()

**Review by abelov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/436)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @cmyers-spirent and @DerangedMonkeyNinja)

___
*[src/modules/network/firehose/server_tcp.cpp, line 149 at r2](https://reviewable.io/reviews/spirent/openperf/436#-MPpI5zSA6-GWnYdT3gX:-MPrUP0J1FZkbwHsjgGf:bb6un1j) ([raw file](https://github.com/spirent/openperf/blob/8f6d74e26f173938d3cafc6e8c69ee2d8e6800e8/src/modules/network/firehose/server_tcp.cpp#L149)):*
<details><summary><i>Previously, cmyers-spirent wrote…</i></summary><blockquote>

since checking it in multiple places now would help to have a  function in the driver to check if blocking  socket read/write should be used e.g.:

  m_driver->needs_blocking_sockets()
</blockquote></details>

Done

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/436)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @abelov-spirent and @cmyers-spirent)

*[a discussion](https://reviewable.io/reviews/spirent/openperf/436#-MQCu0w61cbn1CtwEGIB:-MQCu0w61cbn1CtwEGIC:b-svmlmu) (no related file):*
Please revert the all of the conditional timeout code.  If the non-blocking socket is slower for the DPDK/socket implementation, then there is a bug in that code that needs to be fixed. So, let's fix that bug instead of working around it.

---

**Review by cmyers-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/436)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @cmyers-spirent and @DerangedMonkeyNinja)

*[a discussion](https://reviewable.io/reviews/spirent/openperf/436#-MQCu0w61cbn1CtwEGIB:-MQEDJ4K0knhTruedSkv:bcik6md) (no related file):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Please revert the all of the conditional timeout code.  If the non-blocking socket is slower for the DPDK/socket implementation, then there is a bug in that code that needs to be fixed. So, let's fix that bug instead of working around it.
</blockquote></details>

I think the work contract ended at the end of the year, so I mostly likely that means I will probably be working on this...
I haven't looked at the performance issue but according to Artem, the issue was only with the kernel driver.
Not sure why it would be slower, but constantly calling nonblocking recv() without waiting is not going to help anybody.
I suggested adding select/poll would be a better way to handle this, but there wasn't time to do that.

---

**Comment by cmyers-spirent** [comment]
the network load generator was modified to use epoll (using event_loop) and the firehose protocol fix was added, so this pull request is not needed anymore.

**Pull request closed without merging**
