### PR TITLE
Start timestamp field  to the results (BlockGenerator/MemoryGenerator/CpuGenerator)

### LINKED ISSUE #342: Add rate fields to the results (BlockGeneratorStats/MemoryGeneratorStats/CpuGeneratorTargetStats )
We would like to add ops_rate, bytes_rate, and latency_average to BlockGeneratorStats and MemoryGeneratorStats.

### PR DESCRIPTION
**Pull request by abelov-spirent**
Fixes #342

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/347)

### CODE REVIEW

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 14 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/347)* status: 14 of 29 files reviewed, 1 unresolved discussion (waiting on @abelov-spirent and @DerangedMonkeyNinja)

___
*[api/schema/v1/modules/block.yaml, line 618 at r1](https://reviewable.io/reviews/spirent/openperf/347#-MIg-kyM6o7rYEk9uZ6S:-MIg-kyM6o7rYEk9uZ6T:bxh8ai1) ([raw file](https://github.com/spirent/openperf/blob/ed5d9ad3109032077dd4fcb3689bb50ba7949c60/api/schema/v1/modules/block.yaml#L618)):*
> ```YAML
>       - active
>       - timestamp
>       - start_timestamp
> ```

Suggest `timestamp_first` and `timestamp_last` for consistency with packet results here.

**Review by abelov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/347)* status: 8 of 32 files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

___
*[api/schema/v1/modules/block.yaml, line 618 at r1](https://reviewable.io/reviews/spirent/openperf/347#-MIg-kyM6o7rYEk9uZ6S:-MIh69-3-w4sVbULolr2:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/ed5d9ad3109032077dd4fcb3689bb50ba7949c60/api/schema/v1/modules/block.yaml#L618)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Suggest `timestamp_first` and `timestamp_last` for consistency with packet results here.
</blockquote></details>

Done.

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 3 of 29 files at r1, 9 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/347)* status: 20 of 32 files reviewed, 3 unresolved discussions (waiting on @abelov-spirent and @DerangedMonkeyNinja)

___
*[api/schema/v1/modules/block.yaml, line 602 at r2](https://reviewable.io/reviews/spirent/openperf/347#-MIuYClE6AX5OdlxI4YN:-MIuYClE6AX5OdlxI4YO:b-t10u0t) ([raw file](https://github.com/spirent/openperf/blob/82e6cb22136e30c9df39ae4b417abd961d95f101/api/schema/v1/modules/block.yaml#L602)):*
> ```YAML
>       timestamp_first:
>         type: string
>         description: The ISO8601-formatted date when result has been initialized (generator has been started)
> ```

nit: this explanation could be simplified: "The ISO8601-formatted start time of the generator"
___
*[doc/modules/block.md, line 125 at r2](https://reviewable.io/reviews/spirent/openperf/347#-MIuYfgbDkL6jeRVhfWm:-MIuYfgbDkL6jeRVhfWn:b9rp6pp) ([raw file](https://github.com/spirent/openperf/blob/82e6cb22136e30c9df39ae4b417abd961d95f101/doc/modules/block.md#L125)):*
> ```Markdown
>     },
>     "timestamp": "2020-04-30T00:48:40.283877Z",
>     "start_timestamp": "2020-04-30T00:48:38.891662Z",
> ```

not sure if you noticed, but this doc no longer matches the API schema.
___
*[tests/aat/common/matcher/block.py, line 44 at r2](https://reviewable.io/reviews/spirent/openperf/347#-MIuYtD6D3Uw-Pxqr0pO:-MIuYtD6D3Uw-Pxqr0pP:b-pd577k) ([raw file](https://github.com/spirent/openperf/blob/82e6cb22136e30c9df39ae4b417abd961d95f101/tests/aat/common/matcher/block.py#L44)):*
> ```Python
>         expect(result.active).not_to(be_none)
>         expect(result.timestamp_first).not_to(be_none)
>         expect(result.timestamp_last).not_to(be_none)
> ```

Suggest also verifying that timestamp_last >= timestamp.first.

**Review by abelov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/347)* status: 10 of 32 files reviewed, 2 unresolved discussions (waiting on @DerangedMonkeyNinja)

___
*[doc/modules/block.md, line 125 at r2](https://reviewable.io/reviews/spirent/openperf/347#-MIuYfgbDkL6jeRVhfWm:-MIx5Xw81byA8WNzRovS:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/82e6cb22136e30c9df39ae4b417abd961d95f101/doc/modules/block.md#L125)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

not sure if you noticed, but this doc no longer matches the API schema.
</blockquote></details>

Done.
___
*[tests/aat/common/matcher/block.py, line 44 at r2](https://reviewable.io/reviews/spirent/openperf/347#-MIuYtD6D3Uw-Pxqr0pO:-MIxi2nqEuXgqLqRSXXE:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/82e6cb22136e30c9df39ae4b417abd961d95f101/tests/aat/common/matcher/block.py#L44)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Suggest also verifying that timestamp_last >= timestamp.first.
</blockquote></details>

Done.

**Review by DerangedMonkeyNinja — APPROVED** [review]
:lgtm:

> Reviewed 13 of 21 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/347#-:-MIzQTsy24Uu9yNBHXC_:bnfp4nl)* status: 22 of 33 files reviewed, all discussions resolved

**Pull request merged**
