### PR TITLE
modules/tvlp: use start time from generator

### PR DESCRIPTION
**Pull request by loskutnikov-spirent**
Use start_time from generator statistics, instead of using `now()` method inside TVLP.
Should increases an accuracy of TVLP profile run time.

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/397)

### CODE REVIEW

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
The clock related changes look fine.  Please don't move static functions into classes.  Always prefer free functions over class methods.

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/397#-:-MNOPLZx2rmVi5BGSFNH:bndaee3)* status: all files reviewed, 1 unresolved discussion (waiting on @loskutnikov-spirent)

___
*[src/modules/block/task.cpp, line 53 at r1](https://reviewable.io/reviews/spirent/openperf/397#-MNOP9qu4NH0vgpb93Gq:-MNOP9qu4NH0vgpb93Gr:b-7y99ht) ([raw file](https://github.com/spirent/openperf/blob/d7a80857cd30ef07fb21eef45a79c5cdd5a94b67/src/modules/block/task.cpp#L53)):*
> ```cpp
> }
> 
> static int submit_aio_op(const operation_config& op_config,
> ```

Moving static functions into a class isn't an improvement. :(

**Review by loskutnikov-spirent — COMMENTED** [review]
I moved data types from namespace into class. Functions require this data types, so I had to made it as `static`. I believe that limitation of the scope of data types more important than avoiding `static` methods. 

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/397#-:-MNOV8Ud0dm_91ZTfFWa:b-ki1miy)* status: all files reviewed, 1 unresolved discussion (waiting on @loskutnikov-spirent)

**Review by loskutnikov-spirent — COMMENTED** [review]
Of course I prefer free functions when it possible.

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/397#-:-MNOWKZo4oL0-aNlVrjX:bvgz25p)* status: all files reviewed, 1 unresolved discussion (waiting on @loskutnikov-spirent)

**Review by DerangedMonkeyNinja — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/397#-:-MNTg6a95YJRGQomgxel:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @loskutnikov-spirent)

**Pull request merged**
