### PR TITLE
Assign only available cores to cpu generator workers

### LINKED ISSUE #333: Generated CPU load is limited to 1 core per pod
I have an openperf pod with 4 cores assigned running in openshift environment. When I configure and started CPU generator, I noticed following issues:
1. I cannot configure CPU generator with all 4 cores
2. When I configured CPU load on 3 cores and started CPU generator, the total CPU utilization result showed it's limited to 1 core usage per pod.
(I configured 100% / 20% / 50% loads on each core, and it generated 38.7% / 22% / 38.7% CPU utilization)

### PR DESCRIPTION
**Pull request by abelov-spirent**
Fixes #333 
Cpu generator is trying to assing workers thread to cored by sequential number. But kubernetes can assign random cores to the pod. So we have to find available cores to use by CPU generator.

Signed-off-by: Artem Belov <artem.belov@spirent.com>

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/335)

### CODE REVIEW

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/335)* status: all files reviewed, 1 unresolved discussion (waiting on @abelov-spirent)

___
*[src/modules/cpu/generator.cpp, line 104 at r1](https://reviewable.io/reviews/spirent/openperf/335#-MGtqor7-4rs7uM6xJq-:-MGtqor7-4rs7uM6xJq0:blbvsf8) ([raw file](https://github.com/spirent/openperf/blob/915fd0d9394b956a063780a20425c181baeefb66/src/modules/cpu/generator.cpp#L104)):*
> ```cpp
> std::vector<uint16_t> detect_cores()
> {
>     auto f = std::async(std::launch::async, [] {
> ```

Why are you running this code in another thread?

Generally, code that doesn't seem initially obvious should have comments explaining why it's doing non-obvious things.

**Review by abelov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/335)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

___
*[src/modules/cpu/generator.cpp, line 104 at r1](https://reviewable.io/reviews/spirent/openperf/335#-MGtqor7-4rs7uM6xJq-:-MGvcoq61_y8hTIJLjNa:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/915fd0d9394b956a063780a20425c181baeefb66/src/modules/cpu/generator.cpp#L104)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Why are you running this code in another thread?

Generally, code that doesn't seem initially obvious should have comments explaining why it's doing non-obvious things.
</blockquote></details>

Done.

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/335)* status: all files reviewed, 1 unresolved discussion (waiting on @abelov-spirent)

___
*[src/modules/cpu/generator.cpp, line 104 at r1](https://reviewable.io/reviews/spirent/openperf/335#-MGtqor7-4rs7uM6xJq-:-MGyjjwL4Q0jgte3VRUJ:bv4bm6h) ([raw file](https://github.com/spirent/openperf/blob/915fd0d9394b956a063780a20425c181baeefb66/src/modules/cpu/generator.cpp#L104)):*
<details><summary><i>Previously, abelov-spirent (Artem Belov) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ok, this seems more like a bug with DPDK.  I'd prefer that the DPDK init code get run in a separate thread with the main thread , `op_main` inheriting whatever core mask the user has set.  e.g. this module shouldn't have to work around DPDK issues.

**Review by DerangedMonkeyNinja — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/335)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
