### PR TITLE
modules/memory: add requested memory size check

### LINKED ISSUE #385: Creating a Memory generator buffer_size of a certain size will cause a crash
In my case, buffer_size it's crashing with: 1000000000
```
free -b
              total        used        free      shared  buff/cache   available
Mem:     4136046592   208113664  3762044928    73326592   165888000  3684892672
Swap:             0           0           0
```
OpenPerf logs before it crashes:
```
{"time": "2020-11-12T10:52:43Z", "level": "info", "thread": "op_memory", "tag": "openperf::memory::internal::generator::resize_buffer", "message": "Reallocating buffer (0 => 1000000000)"}
{"time": "2020-11-12T10:52:43Z", "level": "debug", "thread": "op_mem1_ctl", "tag": "openperf::framework::generator::controller::start", "message": "Control thread op_mem1_ctl started"}
{"time": "2020-11-12T10:52:45Z", "level": "debug", "thread": "op_memory", "tag": "openperf::memory::internal::task_memory::config", "message": "Reallocating scratch area (0 --> 8)"}
{"time": "2020-11-12T10:52:45Z", "level": "debug", "thread": "op_mem1_r1", "tag": "openperf::framework::generator::internal::worker::start", "message": "Worker thread started"}
```

The memory generator is created successfully when using a buffer_size of 100000000

### PR DESCRIPTION
**Pull request by loskutnikov-spirent**
Resolve #385

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/390)

### CODE REVIEW

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/390)* status: all files reviewed, 2 unresolved discussions (waiting on @loskutnikov-spirent)

___
*[src/modules/memory/directory.mk, line 36 at r1](https://reviewable.io/reviews/spirent/openperf/390#-MMaOTON0GE4sj2L-qyS:-MMaOTON0GE4sj2L-qyT:b-5ob5jz) ([raw file](https://github.com/spirent/openperf/blob/b45f156669fbe91ab11e67fd6d8b68b04e0be3ec/src/modules/memory/directory.mk#L36)):*
> ```Makefile
> MEMORY_TEST_SOURCES += \
> 	generator.cpp \
> 	info.cpp \
> ```

Where is this file in the changelist?
___
*[src/modules/memory/generator.cpp, line 249 at r1](https://reviewable.io/reviews/spirent/openperf/390#-MMaOZeD0NyQjl4Ixhen:-MMaOZeD0NyQjl4Ixheo:b-1hik0b) ([raw file](https://github.com/spirent/openperf/blob/b45f156669fbe91ab11e67fd6d8b68b04e0be3ec/src/modules/memory/generator.cpp#L249)):*
> ```cpp
>                           + cfg.write.block_size * cfg.write.threads;
> 
>     if (auto free = memory_info::get().free; free < requested_size) {
> ```

This should just be a free function.  Constructing an object to get one value is overkill.

**Review by loskutnikov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/390)* status: all files reviewed, 2 unresolved discussions (waiting on @DerangedMonkeyNinja and @loskutnikov-spirent)

___
*[src/modules/memory/generator.cpp, line 249 at r1](https://reviewable.io/reviews/spirent/openperf/390#-MMaOZeD0NyQjl4Ixhen:-MMbNevJ9EEG_9Qv9jMW:b6dinmk) ([raw file](https://github.com/spirent/openperf/blob/b45f156669fbe91ab11e67fd6d8b68b04e0be3ec/src/modules/memory/generator.cpp#L249)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

This should just be a free function.  Constructing an object to get one value is overkill.
</blockquote></details>

What you mean? This is not an object, just a struct:
```
struct info_t
{
    uint64_t total;
    uint64_t free;
};
```

**Review by loskutnikov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/390)* status: all files reviewed, 2 unresolved discussions (waiting on @DerangedMonkeyNinja)

___
*[src/modules/memory/directory.mk, line 36 at r1](https://reviewable.io/reviews/spirent/openperf/390#-MMaOTON0GE4sj2L-qyS:-MMbN_DfEW5oFfqT0XHM:b-rflyu5) ([raw file](https://github.com/spirent/openperf/blob/b45f156669fbe91ab11e67fd6d8b68b04e0be3ec/src/modules/memory/directory.mk#L36)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Where is this file in the changelist?
</blockquote></details>

This is not separate change, one just required for `memory_info::get()` method call.

**Review by DerangedMonkeyNinja — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/390#-:-MMbmnbv2sQNcVsrUjBG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @loskutnikov-spirent)

**Pull request merged**
