### PR TITLE
Add Golang client infrastructure and source files

### PR DESCRIPTION
**Pull request by dmorton-spirent**
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/487)

### CODE REVIEW

**Review by dmorton-spirent — COMMENTED** [review]
Sorry for the huge code review. The bulk of it is uninteresting auto-generated client sources.

@djoyner if you could give feedback on putting a `go.mod` file in there? `go-swagger` refuses to generate unless the sources are in `$GOPATH/src` or are part of a module.

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/487#-:-M_OK-DF278zO56GhAJ4:b37w21p)* status: 0 of 452 files reviewed, all discussions resolved (waiting on @DerangedMonkeyNinja and @djoyner)

**Review by dmorton-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/487)* status: 2 of 452 files reviewed, 2 unresolved discussions (waiting on @DerangedMonkeyNinja and @djoyner)

___
*[api/client/golang/v1/go.mod, line 1 at r1](https://reviewable.io/reviews/spirent/openperf/487#-M_Q8XAi-RJ6hpo-QJK3:-M_S9wxF8QWWLxqlYlgo:bm5ux7k) ([raw file](https://github.com/spirent/openperf/blob/109191de72b5a6758bd28e420c50972cafe4e41c/api/client/golang/v1/go.mod#L1)):*
<details><summary><i>Previously, djoyner (David Joyner) wrote…</i></summary><blockquote>

Should this be `github.com/spirent/openperf/api/client/golang`?
</blockquote></details>

Yeah, I kinda guessed on this one. On one hand there is already a clear `v1` path to the API spec itself (`api/schema/v1/openperf.yaml`), and followed that here. On the other hand there is only `v1` thus far and no plans I'm aware of to add `v2`. 

This approach is clearer iff we have multiple API versions. 
___
*[api/schema/Makefile, line 8 at r1](https://reviewable.io/reviews/spirent/openperf/487#-M_QAAX_6fcy4Z8sn8wL:-M_SAzvUEAUMpbFOX6_g:b-wne8zz) ([raw file](https://github.com/spirent/openperf/blob/109191de72b5a6758bd28e420c50972cafe4e41c/api/schema/Makefile#L8)):*
<details><summary><i>Previously, djoyner (David Joyner) wrote…</i></summary><blockquote>

Consider the cross-platform approach used here: https://github.com/SpirentOrion/mercury/tree/master/tool/swagger
</blockquote></details>

Thanks, will implement this. Looks cleaner and retains the `go-swagger` version number.

**Review by dmorton-spirent — COMMENTED** [review]
> Reviewed 1 of 455 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/487)* status: 1 of 455 files reviewed, 2 unresolved discussions (waiting on @DerangedMonkeyNinja and @djoyner)

___
*[api/client/golang/v1/go.mod, line 1 at r1](https://reviewable.io/reviews/spirent/openperf/487#-M_Q8XAi-RJ6hpo-QJK3:-Ma_t_QY6nFvlFPW4aV8:bizpfmc) ([raw file](https://github.com/spirent/openperf/blob/109191de72b5a6758bd28e420c50972cafe4e41c/api/client/golang/v1/go.mod#L1)):*
<details><summary><i>Previously, dmorton-spirent (Dan Morton) wrote…</i></summary><blockquote>

Yeah, I kinda guessed on this one. On one hand there is already a clear `v1` path to the API spec itself (`api/schema/v1/openperf.yaml`), and followed that here. On the other hand there is only `v1` thus far and no plans I'm aware of to add `v2`. 

This approach is clearer iff we have multiple API versions. 
</blockquote></details>

As per our side conversation, updated this to remove the `v1` suffix in line with how Go handles modules (https://golang.org/ref/mod#major-version-suffixes)

**Review by djoyner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/487#-:-MacklrY8lVWJjTNaHAe:bnfp4nl)* status: 1 of 455 files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja and @djoyner)

**Pull request merged**
