### PR TITLE
TVLP Dynamic Results

### PR DESCRIPTION
**Pull request by loskutnikov-spirent**
Add Dynamic Results configuration to API.

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/380)

### CODE REVIEW

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 28 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/380)* status: 28 of 36 files reviewed, 2 unresolved discussions (waiting on @DerangedMonkeyNinja and @loskutnikov-spirent)

___
*[src/modules/tvlp/api.hpp, line 92 at r1](https://reviewable.io/reviews/spirent/openperf/380#-MLxaHh9-vbitLKovAIz:-MLxaHhAAzNnKny2y6Si:bsjhou9) ([raw file](https://github.com/spirent/openperf/blob/dce076d3ded78754cec288b71602ea2391a408ff/src/modules/tvlp/api.hpp#L92)):*
> ```cpp
> 
> using item = model::tvlp_configuration_t;
> using list = std::vector<item>;
> ```

Nit: I realize that list is the pre-existing name, but it's a confusing alias for a vector, since they are vastly different structures.
___
*[tests/aat/common/helper/tvlp.py, line 57 at r1](https://reviewable.io/reviews/spirent/openperf/380#-MLxcAfz82k9y-bAKdPK:-MLxcAfz82k9y-bAKdPL:b-bqrbyd) ([raw file](https://github.com/spirent/openperf/blob/dce076d3ded78754cec288b71602ea2391a408ff/tests/aat/common/helper/tvlp.py#L57)):*
> ```Python
> 
> def tvlp_dynamic_results():
>     start = client.models.TrafficProtocol()
> ```

Is this really the correct object?  That's a confusing name if it is...

Also, shouldn't the AAT test dynamic results for every generator (that supports them)?

**Review by loskutnikov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/380)* status: 28 of 36 files reviewed, 1 unresolved discussion (waiting on @loskutnikov-spirent)

___
*[src/modules/tvlp/api.hpp, line 92 at r1](https://reviewable.io/reviews/spirent/openperf/380#-MLxaHh9-vbitLKovAIz:-MLydqVf4DHsCHASTQuV:bu9x20m) ([raw file](https://github.com/spirent/openperf/blob/dce076d3ded78754cec288b71602ea2391a408ff/src/modules/tvlp/api.hpp#L92)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Nit: I realize that list is the pre-existing name, but it's a confusing alias for a vector, since they are vastly different structures.
</blockquote></details>

To avoid the confuse I used only qualified names of API messages. Similar approach was used already in internal API of generators.

**Review by loskutnikov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/380)* status: 21 of 51 files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

___
*[tests/aat/common/helper/tvlp.py, line 57 at r1](https://reviewable.io/reviews/spirent/openperf/380#-MLxcAfz82k9y-bAKdPK:-MM0OpU503Zwb76iyl7n:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/dce076d3ded78754cec288b71602ea2391a408ff/tests/aat/common/helper/tvlp.py#L57)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Is this really the correct object?  That's a confusing name if it is...

Also, shouldn't the AAT test dynamic results for every generator (that supports them)?
</blockquote></details>

Done.

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 11 of 30 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/380)* status: 32 of 51 files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja and @loskutnikov-spirent)

___
*[api/schema/v1/modules/tvlp.yaml, line 413 at r2](https://reviewable.io/reviews/spirent/openperf/380#-MMQPZmv1ATyGM7lqRVT:-MMQPZmw3Sr-JYWBlJVq:b-ul1fd4) ([raw file](https://github.com/spirent/openperf/blob/a1b25f1d2ba1ae1f4921149e3ab46b424c1c881d/api/schema/v1/modules/tvlp.yaml#L413)):*
> ```YAML
>         $ref: "#/definitions/TvlpSeriesStartConfiguration"
> 
>   TvlpSeriesStartConfiguration:
> ```

Suggest changing this name to `TvlpStartSeriesConfiguration`.  That way the hierarchy is obvious in the naming.

**Review by loskutnikov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/380)* status: 29 of 51 files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

___
*[api/schema/v1/modules/tvlp.yaml, line 413 at r2](https://reviewable.io/reviews/spirent/openperf/380#-MMQPZmv1ATyGM7lqRVT:-MMQgbLdCxhdj9RwnMNO:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/a1b25f1d2ba1ae1f4921149e3ab46b424c1c881d/api/schema/v1/modules/tvlp.yaml#L413)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Suggest changing this name to `TvlpStartSeriesConfiguration`.  That way the hierarchy is obvious in the naming.
</blockquote></details>

Done.

**Review by DerangedMonkeyNinja — APPROVED** [review]
:lgtm:

> Reviewed 2 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/380#-:-MMaT2b-34lARCg3Rb5A:bnfp4nl)* status: 31 of 51 files reviewed, all discussions resolved (waiting on @DerangedMonkeyNinja)

**Pull request merged**
