### PR TITLE
Initialize DPDK in dedicated thread

### LINKED ISSUE #337: OpenPerf threads binds to first core of CPU by default
All OpenPerf threads binds to first available CPU core (usually core 0) on creation. 
Problem seems related with DPDK.

### PR DESCRIPTION
**Pull request by loskutnikov-spirent**
Prevent to change OpenPerf affinity mask by DPDK.
Closes #337

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/338)

### CODE REVIEW

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/338)* status: all files reviewed, 5 unresolved discussions (waiting on @loskutnikov-spirent)

*[a discussion](https://reviewable.io/reviews/spirent/openperf/338#-MHGeUpS7gPJgoJlUbJJ:-MHGeUpS7gPJgoJlUbJK:bbfv9ps) (no related file):*
For minor bug fixes like this, please use separate commits for each module. All of the commits can be merged in one commit, however.

Additionally, please tag each commit with 'module: description' (just look at the commit history for examples) so that module changes can be easily managed and merged.

---
___
*[src/framework/core/op_thread.h, line 49 at r1](https://reviewable.io/reviews/spirent/openperf/338#-MHGjSkU9CEibViBxD-1:-MHGjSkU9CEibViBxD-2:b6nmiys) ([raw file](https://github.com/spirent/openperf/blob/fd7b1f7ef8713ec08939c3af5dcb4e3db6adb279/src/framework/core/op_thread.h#L49)):*
> ```objc
>         op_cpuset_delete(current_cpuset);
>         op_cpuset_delete(test_cpuset);
>         throw;
> ```

What actually gets thrown with a `throw`?  Why not rethrow the original error here?  
___
*[src/modules/packetio/init.cpp, line 62 at r1](https://reviewable.io/reviews/spirent/openperf/338#-MHGhmBy7kjvlBGMtjdo:-MHGhmBy7kjvlBGMtjdp:b52ymum) ([raw file](https://github.com/spirent/openperf/blob/fd7b1f7ef8713ec08939c3af5dcb4e3db6adb279/src/modules/packetio/init.cpp#L62)):*
> ```cpp
>     {
>         m_service = std::thread([this]() {
>             op_thread_setname("op_pio");
> ```

Prefer to keep the name op_packetio here since it's more obvious.  I guess `op_packet_io` would fit with the packet naming scheme though.
___
*[src/modules/packetio/drivers/dpdk/eal.cpp, line 329 at r1](https://reviewable.io/reviews/spirent/openperf/338#-MHGhw-g49o33EGBjDKK:-MHGhw-g49o33EGBjDKL:b-2znvb5) ([raw file](https://github.com/spirent/openperf/blob/fd7b1f7ef8713ec08939c3af5dcb4e3db6adb279/src/modules/packetio/drivers/dpdk/eal.cpp#L329)):*
> ```cpp
>      * changes the current thread affinity mask
>      */
>     int parsed_or_err = std::async(rte_eal_init,
> ```

While this technically solves the problem, I'm not a fan of this approach. The reason that the init routine changes the affinity mask is to prevent other threads from interrupting the packet processing threads in order to ensure minimum latency.  So, a better solution here would be to extract the core mask from the DPDK workers and use the complement as the core mask for the other threads. This ends up being a higher level solution that just running the init routine in another thread though as we have to deal with both previously and subsequently launched threads.

Ideas?
___
*[src/modules/packetio/workers/dpdk/worker.cpp, line 1070 at r1](https://reviewable.io/reviews/spirent/openperf/338#-MHGj2yu4ntx_D--Crs1:-MHGj2yu4ntx_D--Crs2:b-rsg327) ([raw file](https://github.com/spirent/openperf/blob/fd7b1f7ef8713ec08939c3af5dcb4e3db6adb279/src/modules/packetio/workers/dpdk/worker.cpp#L1070)):*
> ```cpp
> int main(void* void_args)
> {
>     op_thread_setname(("op_pio_dpdk" + std::to_string(rte_lcore_id())).c_str());
> ```

Suggest op_packet_dpdkXX.

**Review by loskutnikov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/338)* status: all files reviewed, 5 unresolved discussions (waiting on @DerangedMonkeyNinja and @loskutnikov-spirent)

___
*[src/framework/core/op_thread.h, line 49 at r1](https://reviewable.io/reviews/spirent/openperf/338#-MHGjSkU9CEibViBxD-1:-MHH3tsa6rmWnFLhqQgm:bh6y25i) ([raw file](https://github.com/spirent/openperf/blob/fd7b1f7ef8713ec08939c3af5dcb4e3db6adb279/src/framework/core/op_thread.h#L49)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

What actually gets thrown with a `throw`?  Why not rethrow the original error here?  
</blockquote></details>

`throw;` is the short syntax for rethrow original exception.
___
*[src/modules/packetio/init.cpp, line 62 at r1](https://reviewable.io/reviews/spirent/openperf/338#-MHGhmBy7kjvlBGMtjdo:-MHH44wp-TxMBOGRx8Hc:b-xqxvqm) ([raw file](https://github.com/spirent/openperf/blob/fd7b1f7ef8713ec08939c3af5dcb4e3db6adb279/src/modules/packetio/init.cpp#L62)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Prefer to keep the name op_packetio here since it's more obvious.  I guess `op_packet_io` would fit with the packet naming scheme though.
</blockquote></details>

I changed thread name for consistency with `worker` threads. I think `op_pio` not less obvious than `op_packet`, but leaves more symbols for name subthreads.
___
*[src/modules/packetio/workers/dpdk/worker.cpp, line 1070 at r1](https://reviewable.io/reviews/spirent/openperf/338#-MHGj2yu4ntx_D--Crs1:-MHH4dAW19tTt0X_X-lj:b-f5921x) ([raw file](https://github.com/spirent/openperf/blob/fd7b1f7ef8713ec08939c3af5dcb4e3db6adb279/src/modules/packetio/workers/dpdk/worker.cpp#L1070)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Suggest op_packet_dpdkXX.
</blockquote></details>

Too many symbols. First I wanted to use `op_packetio_dpdkXX`, but we have only 15 symbols for name.

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/338)* status: all files reviewed, 2 unresolved discussions (waiting on @DerangedMonkeyNinja and @loskutnikov-spirent)

___
*[src/modules/packetio/drivers/dpdk/eal.cpp, line 329 at r1](https://reviewable.io/reviews/spirent/openperf/338#-MHGhw-g49o33EGBjDKK:-MHHHq7p7nLeEAptDCqg:b-2ct68f) ([raw file](https://github.com/spirent/openperf/blob/fd7b1f7ef8713ec08939c3af5dcb4e3db6adb279/src/modules/packetio/drivers/dpdk/eal.cpp#L329)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

While this technically solves the problem, I'm not a fan of this approach. The reason that the init routine changes the affinity mask is to prevent other threads from interrupting the packet processing threads in order to ensure minimum latency.  So, a better solution here would be to extract the core mask from the DPDK workers and use the complement as the core mask for the other threads. This ends up being a higher level solution that just running the init routine in another thread though as we have to deal with both previously and subsequently launched threads.

Ideas?


</blockquote></details>

One suggestion: Just move the init code to the `packet_io` thread. That way, all of the packet io stuff will end up on the main DPDK core.

**Review by loskutnikov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/338)* status: all files reviewed, 2 unresolved discussions (waiting on @DerangedMonkeyNinja and @loskutnikov-spirent)

*[a discussion](https://reviewable.io/reviews/spirent/openperf/338#-MHGeUpS7gPJgoJlUbJJ:-MHHJJxB1jiNjC2AtIaG:bduo275) (no related file):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

For minor bug fixes like this, please use separate commits for each module. All of the commits can be merged in one commit, however.

Additionally, please tag each commit with 'module: description' (just look at the commit history for examples) so that module changes can be easily managed and merged.
</blockquote></details>

Commit messages was changed.

---

**Review by DerangedMonkeyNinja — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/338)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by DerangedMonkeyNinja — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/338#-:-MHTgTxf-_TmLrXlRGvC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
