### PR TITLE
Deb packaging

### PR DESCRIPTION
**Pull request by smprogsoft**
This PR is essentially the changes offered in the PR https://github.com/Spirent/openperf/pull/391, but with only the deb package support (the RPM support removed). These changes also now add to the package the TLVP plugin. I also added a default `config.yaml` and changed the build container with packages needed for packaging purposes.

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/419)

### CODE REVIEW

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 9 of 18 files at r1, 7 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/419)* status: all files reviewed, 4 unresolved discussions (waiting on @smprogsoft)

*[a discussion](https://reviewable.io/reviews/spirent/openperf/419#-MOIGm4l-DV7KPyrB42h:-MOIGm4oAASPnmLWKEfZ:b-15mysu) (no related file):*
Please cleanup this history before merging!  Since this is all appears to be one focused change, I'd really like to see just one commit for it.  Also, please "rebase and merge" instead of using "create a merge commit" when merging this to master.

---
*[a discussion](https://reviewable.io/reviews/spirent/openperf/419#-MOIHrtU1uEXyd7kbhFP:-MOIHrtU1uEXyd7kbhFQ:b93qa78) (no related file):*
I like and appreciate all the makefile comments.

---
*[a discussion](https://reviewable.io/reviews/spirent/openperf/419#-MOIIgjQ39RLwfGyzNgt:-MOIIgjQ39RLwfGyzNgu:bp9d3q5) (no related file):*
Once the commit history is cleaned up, :lgtm:

---
___
*[pkg/common.mk, line 5 at r2](https://reviewable.io/reviews/spirent/openperf/419#-MOIH8dXEbawppp_d1iJ:-MOIH8dXEbawppp_d1iK:bk2iefh) ([raw file](https://github.com/spirent/openperf/blob/73d87f4d7678c47b7807ab998a8cc5ddeaf5454c/pkg/common.mk#L5)):*
> ```Makefile
> # This file expects the following values to be defined (Note:
> # the error checking op_check_var define is not available yet)
> ifeq ($(PKG_TYPE),)
> ```

This is fine, however FYI there is an existing makefile macro that be used to check if variables are defined

`$(call op_check_vars,PKG_TYPE OP_ROOT)`

**Review by smprogsoft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/419)* status: all files reviewed, 4 unresolved discussions (waiting on @DerangedMonkeyNinja and @smprogsoft)

___
*[pkg/common.mk, line 5 at r2](https://reviewable.io/reviews/spirent/openperf/419#-MOIH8dXEbawppp_d1iJ:-MOIJG1O6QcnIXr9Q_Sk:b2i6k6y) ([raw file](https://github.com/spirent/openperf/blob/73d87f4d7678c47b7807ab998a8cc5ddeaf5454c/pkg/common.mk#L5)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

This is fine, however FYI there is an existing makefile macro that be used to check if variables are defined

`$(call op_check_vars,PKG_TYPE OP_ROOT)`
</blockquote></details>

Yes, I am using that macro (at least the singular version) below in the file. It is just that these values need to be defined before I can include the makefile that has the "checker" definitions.

**Review by smprogsoft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/419)* status: all files reviewed, 4 unresolved discussions (waiting on @DerangedMonkeyNinja and @smprogsoft)

___
*[pkg/common.mk, line 5 at r2](https://reviewable.io/reviews/spirent/openperf/419#-MOIH8dXEbawppp_d1iJ:-MOIKG6b4Q84y2UEflmO:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/73d87f4d7678c47b7807ab998a8cc5ddeaf5454c/pkg/common.mk#L5)):*
<details><summary><i>Previously, smprogsoft wrote…</i></summary><blockquote>

Yes, I am using that macro (at least the singular version) below in the file. It is just that these values need to be defined before I can include the makefile that has the "checker" definitions.
</blockquote></details>

Done.

**Review by smprogsoft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/419)* status: all files reviewed, 3 unresolved discussions (waiting on @DerangedMonkeyNinja)

*[a discussion](https://reviewable.io/reviews/spirent/openperf/419#-MOIGm4l-DV7KPyrB42h:-MObAThe0p4wBwGxQP8z:b-896fix) (no related file):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Please cleanup this history before merging!  Since this is all appears to be one focused change, I'd really like to see just one commit for it.  Also, please "rebase and merge" instead of using "create a merge commit" when merging this to master.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/spirent/openperf/419#-MOIHrtU1uEXyd7kbhFP:-MObAUNt0g4Gvr-UT6Hv:b-896fix) (no related file):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

I like and appreciate all the makefile comments.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/spirent/openperf/419#-MOIIgjQ39RLwfGyzNgt:-MObAUz51hr-hCgRailq:b-896fix) (no related file):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Once the commit history is cleaned up, :lgtm:
</blockquote></details>

Done.

---

**Pull request merged**
