### PR TITLE
Fix tvlp hang due to issues in network load generator

### PR DESCRIPTION
**Pull request by cmyers-spirent**
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/448)

### CODE REVIEW

**Review by cmyers-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/448)* status: 0 of 5 files reviewed, all discussions resolved

___
*[src/modules/network/firehose/protocol.hpp, line 12 at r1](https://reviewable.io/reviews/spirent/openperf/448#-MQWItgCC7irZePhFNf2:-MQWItgCC7irZePhFNf3:bcad37o) ([raw file](https://github.com/spirent/openperf/blob/9bf4ed15e983590dbabfc0f9d86c89d887429013/src/modules/network/firehose/protocol.hpp#L12)):*
> ```cpp
> constexpr auto protocol = "ICP Firehose 2.0";
> const size_t protocol_len = 16;
> ```

This change is from PR https://github.com/Spirent/openperf/pull/436

Added it to see if it was related to the tvlp hang issue, but wasn't related.
message/structure alignment was changed to match inception.
___
*[src/modules/network/firehose/server_tcp.cpp, line 388 at r1](https://reviewable.io/reviews/spirent/openperf/448#-MQWK8Pe3mI5gKApnRo9:-MQWK8Pe3mI5gKApnRoA:b-bz7rpz) ([raw file](https://github.com/spirent/openperf/blob/9bf4ed15e983590dbabfc0f9d86c89d887429013/src/modules/network/firehose/server_tcp.cpp#L388)):*
> ```cpp
>                                    get_state_string(conn.state),
>                                    bytes_left);
>                             conn.state = STATE_ERROR;
> ```

Not clearing bytes_left here was causing it to get stuck in an infinite loop.
___
*[src/modules/packetio/port_handler.cpp, line 132 at r1](https://reviewable.io/reviews/spirent/openperf/448#-MQWKMtv1Ef5GggBm5m6:-MQWKMtv1Ef5GggBm5m7:b-loofxw) ([raw file](https://github.com/spirent/openperf/blob/9bf4ed15e983590dbabfc0f9d86c89d887429013/src/modules/packetio/port_handler.cpp#L132)):*
> ```cpp
> {
>     if (!check_server()) {
>         // Return empty list if not supported
> ```

Seemed more API friendly to return an empty list than Method_Not_Allowed.

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/448)* status: all files reviewed, 1 unresolved discussion (waiting on @cmyers-spirent)

___
*[src/framework/generator/feedback_tracker.cpp, line 7 at r1](https://reviewable.io/reviews/spirent/openperf/448#-MQYG3xh7aeEjEjs4RMM:-MQYG3xh7aeEjEjs4RMN:b-nqtuc4) ([raw file](https://github.com/spirent/openperf/blob/9bf4ed15e983590dbabfc0f9d86c89d887429013/src/framework/generator/feedback_tracker.cpp#L7)):*
> ```cpp
> void feedback_tracker::count_down()
> {
>     std::unique_lock<std::mutex> lock(m_mutex);
> ```

Yuck. What is this for? Is it necessary?

**Review by cmyers-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/448)* status: all files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

___
*[src/framework/generator/feedback_tracker.cpp, line 7 at r1](https://reviewable.io/reviews/spirent/openperf/448#-MQYG3xh7aeEjEjs4RMM:-MQYIuL-88hl6soQqsi3:b1hc5t1) ([raw file](https://github.com/spirent/openperf/blob/9bf4ed15e983590dbabfc0f9d86c89d887429013/src/framework/generator/feedback_tracker.cpp#L7)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Yuck. What is this for? Is it necessary?
</blockquote></details>

class naming is bad, but it is basically a latch/countdownlatch mechanism used in the messaging code to allow the controller to send a broadcast message to all workers and wait for ack response from all workers.

In c++ 20  https://en.cppreference.com/w/cpp/thread/latch

Apparently, there were issues with TVLP network load when it wasn't waiting for the controller to complete start/stop/pause etc. so this was added.

For broadcast message ack wait purposes, it probably isn't a bad way to do it.

**Review by DerangedMonkeyNinja — APPROVED** [review]
:lgtm: once the comment reference below is added.

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/448#-:-MQYU1IO7Usl6nZFQMP_:beanlj4)* status: all files reviewed, 1 unresolved discussion (waiting on @cmyers-spirent)

___
*[src/framework/generator/feedback_tracker.cpp, line 7 at r1](https://reviewable.io/reviews/spirent/openperf/448#-MQYG3xh7aeEjEjs4RMM:-MQYTS5P1t8FoQbpVg28:b-we0802) ([raw file](https://github.com/spirent/openperf/blob/9bf4ed15e983590dbabfc0f9d86c89d887429013/src/framework/generator/feedback_tracker.cpp#L7)):*
<details><summary><i>Previously, cmyers-spirent wrote…</i></summary><blockquote>

class naming is bad, but it is basically a latch/countdownlatch mechanism used in the messaging code to allow the controller to send a broadcast message to all workers and wait for ack response from all workers.

In c++ 20  https://en.cppreference.com/w/cpp/thread/latch

Apparently, there were issues with TVLP network load when it wasn't waiting for the controller to complete start/stop/pause etc. so this was added.

For broadcast message ack wait purposes, it probably isn't a bad way to do it.
</blockquote></details>

Except that this (AFAIK) is the only lock in the code base and we already have 0MQ based functions for synchronization which are used everywhere else.

I hate it.

Can you add a comment, prefixed with "XXX", noting the above with an enjoinder to delete it in the future.

**Review by cmyers-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/448)* status: all files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja)

___
*[src/framework/generator/feedback_tracker.cpp, line 7 at r1](https://reviewable.io/reviews/spirent/openperf/448#-MQYG3xh7aeEjEjs4RMM:-MQYfyLoAAGNiAw1jukW:b-aqkrcw) ([raw file](https://github.com/spirent/openperf/blob/9bf4ed15e983590dbabfc0f9d86c89d887429013/src/framework/generator/feedback_tracker.cpp#L7)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Except that this (AFAIK) is the only lock in the code base and we already have 0MQ based functions for synchronization which are used everywhere else.

I hate it.

Can you add a comment, prefixed with "XXX", noting the above with an enjoinder to delete it in the future.
</blockquote></details>

Ok I will add a FIXME.

Currently the controller code is using 0MQ PUB/SUB for sending broadcast control messages and SUB/PUB for receiving statistics messages and ACK messages back from the workers.
The statistics and ACK messages are Rx in a separate thread than the control messages are Tx from.
Will need to change the code quite a bit to only use 0MQ based functions without another sync mechanism.

**Pull request merged**
