### PR TITLE
Generator Framework synchronized operations

### LINKED ISSUE #429: Last statistics updates can be lost in framework/generator
The most OpenPerf generator use `pause` command to stop generator and then sets zero statistics to prerpare generator for the new start.
The issue is that framework/generator does not guarante receiving all statistics messages on pause command.

### PR DESCRIPTION
**Pull request by loskutnikov-spirent**
Closes #429

Based on #440

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/441)

### CODE REVIEW

**Review by cmyers-spirent — APPROVED** [review]
> Reviewed 45 of 45 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/441)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @loskutnikov-spirent)

**Review by cmyers-spirent — APPROVED** [review]
Looks good to check in once CI tests are passing

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/441#-:-MPmfhHI4ZG1FlOpuO3U:b-yzc2o5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @loskutnikov-spirent)

**Review by loskutnikov-spirent — COMMENTED** [review]
`feedback_tracker` class was changed, because previous version has the race condition troubles.

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/441#-:-MPnmEAU7SIRJDYV68SB:b-eexyli)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @cmyers-spirent and @DerangedMonkeyNinja)

**Review by cmyers-spirent — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/441)* status: all files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja and @loskutnikov-spirent)

___
*[src/framework/generator/feedback_tracker.hpp, line 9 at r2](https://reviewable.io/reviews/spirent/openperf/441#-MPqxdXT0ZM48p5PtgTF:-MPqxdXT0ZM48p5PtgTG:b68o27n) ([raw file](https://github.com/spirent/openperf/blob/d762b5ce6f3ce46e1fa604a87370c7874be8a8a0/src/framework/generator/feedback_tracker.hpp#L9)):*
> ```cpp
> 
> namespace openperf::framework::generator::internal {
> ```

I don't think moving operation_t to feedback_tracker.hpp make sense and m_operation is really not used in any meaningful way in this class.

With latest changes feedback_tracker is only able to support a single operation_t  (which is a good idea) so the m_operation variable can be removed to make feedback_tracker just a count down counter with wait/notify signaling

If you remove m_operation here, then I think operation_t definition should go back to worker.hpp

**Review by cmyers-spirent — APPROVED** [review]
> Reviewed 2 of 6 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/441)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DerangedMonkeyNinja)

**Pull request merged**
