### PR TITLE
contrib/docker: Add init script

### PR DESCRIPTION
**Pull request by loskutnikov-spirent**
Add an initialization script with processing configuration of the OpenPerf from environment variables beginning with OP_ prefix. Excess configuration was removed from the default configuration file.

---
This change is [Reviewable](https://reviewable.io/reviews/spirent/openperf/373)

### CODE REVIEW

**Review by djoyner — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/373)* status: all files reviewed, 3 unresolved discussions (waiting on @DerangedMonkeyNinja and @loskutnikov-spirent)

___
*[contrib/docker/Dockerfile, line 14 at r1](https://reviewable.io/reviews/spirent/openperf/373#-MLNWgmB59EGn1o7yCnW:-MLNWgmB59EGn1o7yCnX:bvrelqe) ([raw file](https://github.com/spirent/openperf/blob/b0cb92dbca2a8700ee314c19c28ebfcad837a4ea/contrib/docker/Dockerfile#L14)):*
> ```Dockerfile
> 
> # Use N/2 cores for making
> RUN make -j$((($(nproc) + 1) / 2)) -C targets/openperf
> ```

Why not just use `nproc`?
___
*[contrib/docker/init.sh, line 15 at r1](https://reviewable.io/reviews/spirent/openperf/373#-MLNXKVG9mWWXZ7rhCuo:-MLNXKVH4rlEKonJwRga:b-x5myne) ([raw file](https://github.com/spirent/openperf/blob/b0cb92dbca2a8700ee314c19c28ebfcad837a4ea/contrib/docker/init.sh#L15)):*
> ```Shell
> 
> # The executable program should be passed through EXECUTABLE
> # environment variable or as first argument of this stript.
> ```

What's the use case for overriding the binary using `$EXECUTABLE`?
___
*[contrib/docker/init.sh, line 22 at r1](https://reviewable.io/reviews/spirent/openperf/373#-MLNWrfPCsCCrR8xNgTU:-MLNWrfQ6ZEwq_e5Og7L:b9o5y0y) ([raw file](https://github.com/spirent/openperf/blob/b0cb92dbca2a8700ee314c19c28ebfcad837a4ea/contrib/docker/init.sh#L22)):*
> ```Shell
> 
> # Print environment variables to console for debugging
> echo ">>> ENV Variables"
> ```

I believe `openperf` uses structured logging output. Writing things like this to the container's `stdout` makes it harder to parse container logs since it mixes unstructured and structured output. If you must do this (which I doubt), then please put it on `stderr`.

Similarly below.

**Review by loskutnikov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/373)* status: all files reviewed, 3 unresolved discussions (waiting on @DerangedMonkeyNinja, @djoyner, and @loskutnikov-spirent)

___
*[contrib/docker/Dockerfile, line 14 at r1](https://reviewable.io/reviews/spirent/openperf/373#-MLNWgmB59EGn1o7yCnW:-MLNf-Dl2TGByFA4a1yf:b-njkv0r) ([raw file](https://github.com/spirent/openperf/blob/b0cb92dbca2a8700ee314c19c28ebfcad837a4ea/contrib/docker/Dockerfile#L14)):*
<details><summary><i>Previously, djoyner (David Joyner) wrote…</i></summary><blockquote>

Why not just use `nproc`?
</blockquote></details>

I prefer don't give all available cores to one task, because another applications needs CPU time too. I think `N/2` cores is the optimal value.
___
*[contrib/docker/init.sh, line 15 at r1](https://reviewable.io/reviews/spirent/openperf/373#-MLNXKVG9mWWXZ7rhCuo:-MLNfcsD147akt1PlX29:b-9f67f3) ([raw file](https://github.com/spirent/openperf/blob/b0cb92dbca2a8700ee314c19c28ebfcad837a4ea/contrib/docker/init.sh#L15)):*
<details><summary><i>Previously, djoyner (David Joyner) wrote…</i></summary><blockquote>

What's the use case for overriding the binary using `$EXECUTABLE`?
</blockquote></details>

There is no `use case for overriding`. Using the variable lets to define the executable file name in one place, instead of several. This allows simplify scripts support.

**Review by loskutnikov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/373)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @DerangedMonkeyNinja and @djoyner)

___
*[contrib/docker/init.sh, line 22 at r1](https://reviewable.io/reviews/spirent/openperf/373#-MLNWrfPCsCCrR8xNgTU:-MLNiXDG4iWPiUJKeidt:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/b0cb92dbca2a8700ee314c19c28ebfcad837a4ea/contrib/docker/init.sh#L22)):*
<details><summary><i>Previously, djoyner (David Joyner) wrote…</i></summary><blockquote>

I believe `openperf` uses structured logging output. Writing things like this to the container's `stdout` makes it harder to parse container logs since it mixes unstructured and structured output. If you must do this (which I doubt), then please put it on `stderr`.

Similarly below.
</blockquote></details>

Done.

**Review by djoyner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/373)* status: all files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja and @loskutnikov-spirent)

___
*[contrib/docker/Dockerfile, line 14 at r1](https://reviewable.io/reviews/spirent/openperf/373#-MLNWgmB59EGn1o7yCnW:-MLNwvct73RARoAwXsL_:b51cp46) ([raw file](https://github.com/spirent/openperf/blob/b0cb92dbca2a8700ee314c19c28ebfcad837a4ea/contrib/docker/Dockerfile#L14)):*
<details><summary><i>Previously, loskutnikov-spirent (Anatoly Loskutnikov) wrote…</i></summary><blockquote>

I prefer don't give all available cores to one task, because another applications needs CPU time too. I think `N/2` cores is the optimal value.
</blockquote></details>

Please don't hardcode personal preferences. If we were building this in a K8S pod then this choice wouldn't make sense. Perhaps add a command line option to the script? Default should be `nproc`.
___
*[contrib/docker/init.sh, line 15 at r1](https://reviewable.io/reviews/spirent/openperf/373#-MLNXKVG9mWWXZ7rhCuo:-MLNxLPTBpmjyncHanPe:b-nec2kw) ([raw file](https://github.com/spirent/openperf/blob/b0cb92dbca2a8700ee314c19c28ebfcad837a4ea/contrib/docker/init.sh#L15)):*
<details><summary><i>Previously, loskutnikov-spirent (Anatoly Loskutnikov) wrote…</i></summary><blockquote>

There is no `use case for overriding`. Using the variable lets to define the executable file name in one place, instead of several. This allows simplify scripts support.
</blockquote></details>

Ok, makes sense.

**Review by loskutnikov-spirent — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/373)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @DerangedMonkeyNinja and @djoyner)

___
*[contrib/docker/Dockerfile, line 14 at r1](https://reviewable.io/reviews/spirent/openperf/373#-MLNWgmB59EGn1o7yCnW:-MLO-QTvANx-MYxT1zTy:b-896fix) ([raw file](https://github.com/spirent/openperf/blob/b0cb92dbca2a8700ee314c19c28ebfcad837a4ea/contrib/docker/Dockerfile#L14)):*
<details><summary><i>Previously, djoyner (David Joyner) wrote…</i></summary><blockquote>

Please don't hardcode personal preferences. If we were building this in a K8S pod then this choice wouldn't make sense. Perhaps add a command line option to the script? Default should be `nproc`.
</blockquote></details>

Done.

**Review by djoyner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/373#-:-MLQBwPm2DLGf6mzxi29:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DerangedMonkeyNinja)

**Review by DerangedMonkeyNinja — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/spirent/openperf/373#-:-MLT19ej8oNWr6thEDR6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DerangedMonkeyNinja)

**Pull request merged**
